--
-- PostgreSQL database dump
--

\restrict AQ0bZAZyviCpome1xLcGiXdb2D8HXXeOUVNpwO8NFzIN5Lx2PyAIBqlfIMscbqe

-- Dumped from database version 17.6
-- Dumped by pg_dump version 18.0

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA public;


--
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON SCHEMA public IS 'standard public schema';


--
-- Name: age_category; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.age_category AS ENUM (
    '-15',
    '16-17',
    '18+'
);


--
-- Name: gender; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.gender AS ENUM (
    'maennlich',
    'weiblich'
);


--
-- Name: role; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.role AS ENUM (
    'teacher',
    'assistent'
);


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: grades_table; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.grades_table (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    points_min integer NOT NULL,
    grade double precision NOT NULL,
    age_category public.age_category,
    gender public.gender,
    average_points_per_category bigint
);


--
-- Name: points_table; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.points_table (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    sport_code text NOT NULL,
    performance numeric NOT NULL,
    points integer NOT NULL,
    gender public.gender DEFAULT 'maennlich'::public.gender NOT NULL
);


--
-- Name: profiles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.profiles (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    role text NOT NULL,
    username text NOT NULL,
    password text NOT NULL
);


--
-- Name: results; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.results (
    id integer NOT NULL,
    student_id uuid,
    sport text NOT NULL,
    "group" text NOT NULL,
    attempt_results jsonb,
    heights jsonb,
    scores jsonb,
    best_result double precision,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    points int,
    skipped boolean DEFAULT false,
    grade real
);


--
-- Name: results_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.results_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: results_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.results_id_seq OWNED BY public.results.id;


--
-- Name: sportdays; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sportdays (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    date date
);


--
-- Name: sportdays_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.sportdays ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sportdays_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sports; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sports (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    name text NOT NULL,
    code text NOT NULL,
    measure text,
    mesure_unit_short text,
    attempts smallint DEFAULT '3'::smallint NOT NULL,
    check_fail boolean DEFAULT false NOT NULL,
    time_measure boolean DEFAULT false NOT NULL,
    svg_url text
);


--
-- Name: COLUMN sports.time_measure; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.sports.time_measure IS 'To calculate if a higher score is better or noct';


--
-- Name: students; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.students (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    name text NOT NULL,
    surname text NOT NULL,
    date_of_birth date NOT NULL,
    class_group text NOT NULL,
    assistant_bool boolean DEFAULT false,
    present_bool boolean DEFAULT true,
    created_at timestamp with time zone DEFAULT now(),
    total_points int,
    age_category public.age_category,
    grade real,
    gender public.gender
);


--
-- Name: results id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.results ALTER COLUMN id SET DEFAULT nextval('public.results_id_seq'::regclass);


--
-- Data for Name: grades_table; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.grades_table (id, points_min, grade, age_category, gender, average_points_per_category) FROM stdin;
66e0d15b-85b7-4920-ad3f-38eca8a1190e	48	2	-15	maennlich	8
a649c863-c6b9-4cdc-aea1-4628a07726d8	84	2.5	-15	maennlich	14
14fa1880-890a-49c4-a2c7-65f6991b7b17	120	3	-15	maennlich	20
67073076-c39c-4992-8301-77c89057fb63	156	3.5	-15	maennlich	26
7b9b0f08-0050-4385-8ab7-e8e6071579ff	192	4	-15	maennlich	32
5025b14c-6c25-44df-b031-7f3f8ea5f91a	228	4.5	-15	maennlich	38
e363c78d-8c7b-4900-ad40-99b7f9504628	264	5	-15	maennlich	44
68a97e4e-74cc-4de9-8a00-a2be80bacf04	300	5.5	-15	maennlich	50
4f609692-8efc-4a43-8266-da4164908b88	336	6	-15	maennlich	56
b20df3d0-7c28-4e67-ae8d-015ae83014ad	36	2	16-17	maennlich	6
090806e2-1188-40ba-b19c-a26c1531b8da	72	2.5	16-17	maennlich	12
66e4ef52-3893-4cbb-99c5-0fb573355fa4	108	3	16-17	maennlich	18
b3a05656-3d66-4a17-a107-aad1da693ca4	150	3.5	16-17	maennlich	25
eefd911f-6560-4423-9d58-22005f9d6e55	192	4	16-17	maennlich	32
dc790323-8b7c-4357-a341-8500e3a6b5c5	234	4.5	16-17	maennlich	39
67820b0a-12fe-427f-97d6-86d7bc8eaf11	276	5	16-17	maennlich	46
38570393-8db5-4e8f-94e7-35ca7f929074	318	5.5	16-17	maennlich	53
2e3b7edd-fb0b-4d20-8164-5ec4228ed2d8	360	6	16-17	maennlich	60
e215d689-fe85-4c80-99b4-c87d60f5487c	36	2	18+	maennlich	6
7f6f2835-a8ae-4efd-adcf-0571b2fe00b0	72	2.5	18+	maennlich	12
f6830af0-6291-418b-8138-c6c790fba900	108	3	18+	maennlich	18
9d873fe0-f386-4edb-abc7-0174f30f5149	156	3.5	18+	maennlich	26
f8210142-e871-4ffa-8db2-ec2d7c359198	204	4	18+	maennlich	34
d874ef8d-c447-4347-a5c9-e8d552df0b4e	252	4.5	18+	maennlich	42
72b441e2-e345-46d2-b87a-e28843f3c0a1	300	5	18+	maennlich	50
4ffcf3cf-9151-464c-995a-f2c22a97e3d3	348	5.5	18+	maennlich	58
24bb7f32-392b-4312-84f6-929659220674	396	6	18+	maennlich	66
8279db80-6d6a-4497-9057-a36c5431fe7f	36	2	-15	weiblich	6
ddc4dcbb-b62f-4b04-80a6-0ef9e7566fea	66	2.5	-15	weiblich	11
aec17013-b443-4f70-b870-5067201f688e	96	3	-15	weiblich	16
1670ad6f-d36e-4f28-9ca8-dc0743451794	126	3.5	-15	weiblich	21
83d9259d-b441-45bc-91c8-5baefe95e55b	156	4	-15	weiblich	26
cddb5c18-c697-4d05-9b0f-443a075fe6ba	186	4.5	-15	weiblich	31
d31bc419-abcd-4778-b35d-540ae0aa92fb	216	5	-15	weiblich	36
04d3ef90-c129-4427-a565-ae5c00d39ebd	246	5.5	-15	weiblich	41
0cc77f16-f74a-4648-bf63-2d2b62db1b35	276	6	-15	weiblich	46
68c4cb8c-d1d6-472b-a300-fffa9ed0c2ce	42	2	16-17	weiblich	7
6a49d784-4dc5-4f89-89d6-74d19dffbcfd	72	2.5	16-17	weiblich	12
f185d5dc-6481-4632-8835-5ea6b4cc5c5c	102	3	16-17	weiblich	17
40e8723f-17b4-44eb-936d-9bc8f775de7d	132	3.5	16-17	weiblich	22
4cb36156-8f6b-4af8-a41d-52d2a018edc0	162	4	16-17	weiblich	27
3f8f1309-226e-4283-b8c8-376471b8daba	198	4.5	16-17	weiblich	33
c98bbbda-2427-42fa-a921-f68d5e8c35bb	234	5	16-17	weiblich	39
f5df55e2-653d-4350-b63d-8ad63c42e07a	270	5.5	16-17	weiblich	45
c2bad3eb-cef2-4b5d-9120-d5cc17fecd19	306	6	16-17	weiblich	51
005d391d-1dec-4e1c-baa9-906ca3f4d76d	48	2	18+	weiblich	8
5064cc33-b4ee-48ae-a4b3-cab7208bb197	78	2.5	18+	weiblich	13
f10d939b-2b11-4f9b-90bd-9d85d0a1bd8b	108	3	18+	weiblich	18
a8358d60-169b-4f0b-bb2b-4e49d6cd2928	138	3.5	18+	weiblich	23
d33cd47b-489c-4274-889d-7235589d5db1	168	4	18+	weiblich	28
6778cbed-602a-4b7e-9d52-f4504875832f	210	4.5	18+	weiblich	35
f85f0072-a064-4b95-bdac-9b51b5422827	252	5	18+	weiblich	42
f78c54d0-f8b3-42f3-a7e2-7b4c315aff1e	294	5.5	18+	weiblich	49
1e0850f4-1dba-4e74-bba7-7422984096a3	336	6	18+	weiblich	56
\.


--
-- Data for Name: points_table; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.points_table (id, sport_code, performance, points, gender) FROM stdin;
7ed6923f-7fb7-43f6-b44d-b724a6ad8360	80m	14.56	1	maennlich
28bb234b-0913-4027-a4ff-3d513f1ac3d0	80m	14.46	2	maennlich
6ada15fb-c207-4222-90f8-e31c73a173b2	80m	14.36	3	maennlich
acf4e9af-3efd-4804-a04c-d708234c1013	80m	14.26	4	maennlich
93bfeabd-cace-4193-a1ef-e2675bc72565	80m	14.16	5	maennlich
958ed282-a902-4f2a-afed-f1f77b030678	80m	14.07	6	maennlich
18ca1b12-a766-40e8-b5c0-648d2ee8fa0a	80m	13.97	7	maennlich
e8fdecd3-999b-493b-8659-dbb841cd25f2	80m	13.88	8	maennlich
b49f57c0-847e-415e-b9c5-5fd6602ecb53	80m	13.79	9	maennlich
632719e2-ba46-4ca9-b80c-c9aeb1908cb4	80m	13.7	10	maennlich
9dc46d40-f462-4992-8120-93f1d28061b7	80m	13.61	11	maennlich
8f53a193-9c23-4317-b1b4-bcdd31f7398e	80m	13.52	12	maennlich
5a2526fd-e981-4560-bad1-324cd9918fec	80m	13.43	13	maennlich
339cd332-255d-4fe7-93cd-2e4f2ba2df65	80m	13.34	14	maennlich
105cd140-2876-48d0-82e0-03d53f86fbdd	80m	13.26	15	maennlich
3f778c75-1600-462c-aba2-e87dc8ed17aa	80m	13.18	16	maennlich
5830be2f-8f8e-4021-a8ea-f33af9335cb8	80m	13.09	17	maennlich
5f9c30f2-3b99-4633-98a2-a867d53cdf07	80m	13.01	18	maennlich
1274d9d2-d2b5-4701-9f0a-778686157b35	80m	12.93	19	maennlich
7cc20c1e-24d2-4f77-a660-853c1d03e64d	80m	12.85	20	maennlich
b7845333-02bc-4879-b41e-2afdc6254b7a	80m	12.77	21	maennlich
d6be8831-4e0a-4cc9-849d-9e42f1dca700	80m	12.69	22	maennlich
043b057b-c242-471a-ab9c-6623c1afb89b	80m	12.62	23	maennlich
a6f744bd-1f1f-4ef3-97fc-45795d174faa	80m	12.54	24	maennlich
c1021dfa-b024-4b0f-bdec-5613a5e9c369	80m	12.46	25	maennlich
8158119d-3855-4a81-acb8-dd4a7b090b85	80m	12.39	26	maennlich
0db8cc62-1905-4570-b284-c5a47518cc44	80m	12.32	27	maennlich
de40bca3-033c-458d-9d32-76431b8f4343	80m	12.25	28	maennlich
af4059da-4cd2-4dfe-811c-c5a0868e1b8e	80m	12.17	29	maennlich
506a9de1-cd74-4e9e-bc6d-18a0a2682b20	80m	12.1	30	maennlich
ea8f316d-5b3e-4723-804f-bab79a77109e	80m	12.03	31	maennlich
edc76bee-c02c-4890-9be6-deed98ac45ae	80m	11.96	32	maennlich
b529ff97-bcc6-475d-8969-db00117dc71f	80m	11.9	33	maennlich
e916853f-a772-453d-b769-cc5815230297	80m	11.83	34	maennlich
d0594807-0c57-4c96-95f0-e3a79e33436b	80m	11.76	35	maennlich
91147164-4fd6-4b73-8b48-af892908eb9f	80m	11.69	36	maennlich
cdffa3ac-ac4c-4729-8dba-9b0b1238469d	80m	11.63	37	maennlich
7bda0f75-efde-4364-804f-bc715361fad0	80m	11.56	38	maennlich
c859b3d0-6f20-4a68-b7cf-31ecea87c086	80m	11.5	39	maennlich
a08b787f-70c9-4484-84c2-3d10143a8ac8	80m	11.44	40	maennlich
da961542-3868-4d15-bf36-2f9bb96daf98	80m	11.38	41	maennlich
2b7b18e6-3c08-4a35-a733-a2e39abba6ba	80m	11.31	42	maennlich
03605b6f-6a08-4424-86e1-062c0a64de1f	80m	11.25	43	maennlich
2fd0ddb0-18bb-4aaf-aa70-d14299067660	80m	11.19	44	maennlich
d099e6c2-13cd-4153-ad9b-07d7da3e0275	80m	11.13	45	maennlich
343f22f2-3b1b-415d-bb82-f8c7cab99fa8	80m	11.07	46	maennlich
c9fa8b3f-ed8a-4ee2-9541-3f8798f29324	80m	11.01	47	maennlich
89914f23-a460-4f44-9e92-b76b2fba4c5b	80m	10.96	48	maennlich
2f6e6cf8-f347-4d34-a1bb-348d91278091	80m	10.9	49	maennlich
61c3666d-b8d2-41f7-83f2-a8902214ee35	80m	10.84	50	maennlich
11e2a893-66a8-43f8-8507-06ecd429688f	80m	10.79	51	maennlich
10c642ca-d25c-43f7-be97-7e670b43ea1c	80m	10.73	52	maennlich
115490e0-6be5-489f-b6c5-8210b5b05212	80m	10.68	53	maennlich
1d01a607-fe6b-4abd-b656-13b88450c56e	80m	10.62	54	maennlich
3edf2021-d631-46f6-abe8-d3262683dcdc	80m	10.57	55	maennlich
6bcc33c6-bff7-4c9d-a792-c7a3c69b1f50	80m	10.51	56	maennlich
889b0d3c-08aa-417d-84be-07e717b2c11e	80m	10.46	57	maennlich
339ba80c-4455-46fa-bbbe-70d21f4c1c15	80m	10.41	58	maennlich
c6c54cfa-e306-4957-bf87-dd86a90f4c73	80m	10.36	59	maennlich
ecb0a01f-d21a-4a71-8cb9-c90dee385e13	80m	10.31	60	maennlich
d721350c-f98d-4b4f-999b-ee3beff4af3b	80m	10.25	61	maennlich
13ae4aea-2114-4aa5-b8ff-9b783c08a832	80m	10.2	62	maennlich
e0c2b9e7-7435-4576-bdf4-e67775f24355	80m	10.15	63	maennlich
88824f17-1f49-47ea-bddf-4eb0c62ef5b2	80m	10.1	64	maennlich
5f036d03-dc59-4452-857c-ce6e564518ed	80m	10.06	65	maennlich
67500959-a507-4301-bf61-5b5aae33f2a4	80m	10.01	66	maennlich
16101b84-ce39-43a0-a33a-ce6c64259481	80m	9.96	67	maennlich
53ed323b-0bd4-4a6f-ae6d-3c54fd0ab25e	80m	9.91	68	maennlich
874e3dfe-b8f8-4e48-8aa7-c2951e3ed6de	80m	9.87	69	maennlich
650ba4b0-4808-4319-bbdc-6ff1302997f0	80m	9.82	70	maennlich
bc987025-3827-4ca9-a65b-df86e9cf4a6d	80m	9.77	71	maennlich
d54a99fc-bce5-421c-86c4-314bb0200daa	80m	9.73	72	maennlich
84684f6d-e7f3-4cbc-a30b-212872052f5b	80m	9.68	73	maennlich
28c4a704-2156-4cc9-93e6-c8558b51aeba	80m	9.64	74	maennlich
c8073f8b-15f7-4be8-8161-7ce8669bb52f	80m	9.59	75	maennlich
9f9d3952-34cb-4393-8292-5ddf7939a675	80m	9.55	76	maennlich
6eda2667-9968-4961-984a-53861420fd8a	80m	9.5	77	maennlich
469b7c38-41f3-457c-8616-dce7a1069c37	80m	9.46	78	maennlich
5eae2e39-4007-4beb-80a4-280eee049640	80m	9.42	79	maennlich
fd256941-ee24-4266-84ed-3aa4d2755a5a	80m	9.38	80	maennlich
d01ac794-75bc-46bf-9070-9f21b8993421	80m	9.33	81	maennlich
d9cd5841-d852-425d-bde9-ea088951047a	80m	9.29	82	maennlich
c7bfc0b6-1649-44d2-8790-2c14f44e36b1	80m	9.25	83	maennlich
b8064945-9c3d-4dac-bd44-372c3efd7231	80m	9.21	84	maennlich
1640931f-2d6d-4cc8-984c-4922f9a684ca	80m	9.17	85	maennlich
3e826444-80ab-4854-8962-294a2b8c7893	80m	9.13	86	maennlich
9b3181da-4be3-466e-b77d-cdd47ee7ecb2	80m	9.09	87	maennlich
8196fd18-abfc-4bd8-9692-ccf06301d78c	80m	9.05	88	maennlich
1bf8cddf-c6b8-4223-8431-b42acf45f36f	80m	9.01	89	maennlich
4097e041-e529-4929-9ca7-6bc83a01bc62	80m	8.97	90	maennlich
b0ba3284-da80-4f21-92f0-28f2d53ac7d6	80m	8.93	91	maennlich
0d47c371-d08d-4230-9929-72c8318771ab	80m	8.9	92	maennlich
d3f74c0d-2e48-4d6e-bb3a-f505af9abe40	80m	8.86	93	maennlich
4e7c7674-cf2b-4176-8902-88fb000c0cd1	80m	8.82	94	maennlich
03349fbb-a917-433d-8b95-8f705e013737	80m	8.78	95	maennlich
321cf339-ed0d-4968-afbb-bce520eceee6	80m	8.75	96	maennlich
7c78002d-46af-4591-b0e0-8324acacd24a	80m	8.71	97	maennlich
8259df57-f47e-4d38-b898-f2ae655ea85c	80m	8.67	98	maennlich
3cb765d5-78a5-44d3-9cf4-a9d0518382d1	80m	8.64	99	maennlich
98f15b6e-d0ba-411f-ae1a-4207ac9f0113	80m	8.6	100	maennlich
a4776aa4-4a66-4021-b1ad-acea2a6d5fe6	kugel	6.25	21	maennlich
c337c903-7e07-4974-a2d3-5cee6b6b8641	kugel	6.34	22	maennlich
8c6efa13-3692-4ca3-90ca-38835bf943b2	kugel	6.44	23	maennlich
959e8f27-87e9-459f-ae41-7b54a254d963	kugel	6.54	24	maennlich
384596b8-09ed-46f8-b452-ccf6fd2f34fd	kugel	6.64	25	maennlich
fb1424be-9bd8-45ca-b904-8f2dc28fd680	kugel	6.74	26	maennlich
598d1274-8902-47fd-964a-c5fa65eebb6d	kugel	6.84	27	maennlich
5b05768f-fbba-4436-aac6-8bdb53e195fa	kugel	6.94	28	maennlich
e9aab496-0a64-45ca-8124-492e922dcf94	kugel	7.05	29	maennlich
29783eee-243e-464b-ad90-e114568509a5	kugel	7.15	30	maennlich
2d689c12-7592-488f-b515-f5da23f7c43c	kugel	7.25	31	maennlich
ba72bbb7-ed6c-4d35-92c1-129d35e07c62	kugel	7.36	32	maennlich
b1b2b447-bd29-4e01-bb7b-f7dcd52a1259	kugel	7.46	33	maennlich
29af756e-7497-49aa-b503-f5f1aa72a312	kugel	7.57	34	maennlich
6fb0395f-4c0d-4d71-b3eb-294c367f3fc9	kugel	7.68	35	maennlich
d6ab5621-904e-4350-979d-28ac82767988	kugel	7.78	36	maennlich
755f0791-d8b4-4d0b-b6e5-36432d981b1d	kugel	7.89	37	maennlich
cebf25a4-5995-43a3-ba35-b78f86f58690	kugel	8	38	maennlich
acc40827-6b37-4755-a613-b022098673cc	kugel	8.11	39	maennlich
05995bac-0ff1-485c-ba60-04edf9e8db14	kugel	8.22	40	maennlich
9f2b9964-89aa-48e7-ae2b-c3781b53b7c2	kugel	8.33	41	maennlich
cef15668-1193-44d6-97ce-75008600353d	kugel	8.45	42	maennlich
02308ca6-ee88-4807-83ed-c81a51c0e2da	kugel	8.56	43	maennlich
0dd45894-195b-4a68-9c67-d5d6db6e5a7d	kugel	8.67	44	maennlich
ee9841cc-dada-4108-9b75-fa0363c6b6a4	kugel	8.79	45	maennlich
d03da23b-6f32-4492-81b4-5fcc6ad989dc	kugel	8.9	46	maennlich
37eb9a4c-7293-4132-9a27-f9b5d5c7b640	kugel	9.02	47	maennlich
2ce61c68-69ae-48c3-ae2b-60cd2a9776e9	kugel	9.14	48	maennlich
c021a523-6236-4925-bd82-e21c535eedb5	kugel	9.25	49	maennlich
4e014c7b-a9ee-4992-959e-b89c79941a97	kugel	9.37	50	maennlich
c7766f10-517a-47b4-98e4-49d595064ec8	kugel	9.49	51	maennlich
21fc8c49-0197-469d-8e14-c409c6ca880a	kugel	9.61	52	maennlich
8fc8f2f3-33fc-4d55-a41f-c7c883f54a4a	kugel	9.73	53	maennlich
f4dc9892-b699-43c9-b9d3-65b3c3be87a0	kugel	9.85	54	maennlich
2122f2a4-1371-41d6-a493-ffe32ebca2fd	kugel	9.98	55	maennlich
630582a8-9412-4ef5-8f5d-44bf5d17eb48	kugel	10.1	56	maennlich
6f0ff5d1-4d6d-492c-9b2d-75f93dc97213	kugel	10.22	57	maennlich
4db8661f-5a38-4d37-8fe5-7db186523fa2	kugel	10.35	58	maennlich
de5af724-a22e-440f-bf4c-592e22e4c7a9	kugel	10.47	59	maennlich
979d781f-d89b-4d35-b6f2-e00b7a90f232	kugel	10.6	60	maennlich
f09330de-3e39-45be-935e-fbb0ba021fe1	kugel	10.72	61	maennlich
af5181d7-05a7-4f40-a1d5-80cbfc82a0dd	kugel	10.85	62	maennlich
470e59f5-4d65-4c99-b35d-bb388dbf6963	kugel	10.98	63	maennlich
bd170740-b075-448b-a64e-ce59f65d5584	kugel	11.11	64	maennlich
65aae749-dd0d-4f35-80ce-a59840b2e285	kugel	11.24	65	maennlich
34fb91ca-dcc5-4216-b8e6-223e7c19ebf5	kugel	11.37	66	maennlich
460368b6-f2bc-494e-a8b3-042e766e6a4b	kugel	11.5	67	maennlich
df6ee581-dbaa-467b-9c4a-7a6eed58ac9a	kugel	11.63	68	maennlich
deed9cae-237e-4476-a7d5-31a7b230d0d1	kugel	11.77	69	maennlich
0f9a8a1d-0bd8-484f-ba25-319ad0e54134	kugel	11.9	70	maennlich
93e04119-6987-4aef-afdc-cb6a15841a59	kugel	12.03	71	maennlich
7efb705b-eff3-4dec-8ca4-e1c1165c6a6a	kugel	12.17	72	maennlich
97b693fb-4aff-4deb-bdf2-ab08272b29a9	kugel	12.3	73	maennlich
7db8a232-5154-4fa5-bfee-2c0df2a5c9e6	kugel	12.44	74	maennlich
f32525e1-ef2f-493c-ac94-94e2e8cfd3a5	kugel	12.58	75	maennlich
ef79b502-629b-4f77-8498-25c6969a2187	kugel	12.71	76	maennlich
d3c32599-c8af-499f-9f73-d03b86caa62b	kugel	12.85	77	maennlich
3623c90b-90c3-4c98-bb1e-09c62144c3d5	kugel	12.99	78	maennlich
6c9790a1-190a-43bc-8ea9-9d15036e332b	kugel	13.13	79	maennlich
67ecb85a-9428-4f7a-b4cc-cc160f17cf0b	kugel	13.27	80	maennlich
d5c5c7a7-26fa-4345-b7cc-55f2e1b9b325	kugel	13.42	81	maennlich
44813c76-d5ae-4d18-9920-65ac8c6dbf5d	kugel	13.56	82	maennlich
e75f62ca-398e-487c-b4e1-11952b123900	kugel	13.7	83	maennlich
65214afe-d4fe-4a93-8eec-598f55dcfb8d	kugel	13.85	84	maennlich
2ae0e843-6a35-4366-b4ca-69d5fa9ca386	kugel	13.99	85	maennlich
e036cd85-a6b9-483c-a646-1a6c48a73c5a	kugel	14.14	86	maennlich
b242e1cb-6024-4ef6-8e7c-4b86485b6bfe	kugel	14.28	87	maennlich
e641fb67-0934-4b67-933c-481f23de45cd	kugel	14.43	88	maennlich
5d589050-842b-48d1-997b-590d3b9ebbf6	kugel	14.58	89	maennlich
58becf90-8ca3-4079-b211-17bff8757bca	kugel	14.73	90	maennlich
a6d06333-c910-44cc-84ca-ecb762ea56be	kugel	14.87	91	maennlich
5d34fd0f-b4cf-489c-ba24-c8ebf22469f3	kugel	15.02	92	maennlich
7f070fcf-6019-47fc-b150-59a5ac23c6c2	kugel	15.18	93	maennlich
5122869d-671b-4feb-868a-1dfd30f76ac9	kugel	15.33	94	maennlich
4c85e699-59a8-4396-87ce-86a1bb4e168e	kugel	15.48	95	maennlich
b1f6d09a-40c2-47f9-a015-1c85e300c63c	kugel	15.63	96	maennlich
0aa63f7b-efb3-4d88-a1aa-5409cd6e1e77	kugel	15.79	97	maennlich
8d06ff69-e2b2-4e52-b742-54a58a45c155	kugel	15.94	98	maennlich
01992e8e-2d80-433d-9421-9153970c23d6	kugel	16.1	99	maennlich
d9759bc5-ca69-4e49-b4e5-abcd5e82104b	kugel	16.25	100	maennlich
560fe327-4edb-4e8a-a4a0-1cbdde6c0cee	kugel	5.86	21	weiblich
3cb5ea21-ec00-4506-9aa6-88d85db40395	kugel	5.92	22	weiblich
734bd091-865f-455f-a30a-1b56a3b66174	kugel	5.98	23	weiblich
27533828-594a-4bd0-b6fe-681fbd9b6ebe	kugel	6.04	24	weiblich
d33ee52e-3bf1-491a-9371-56305435d398	kugel	6.11	25	weiblich
bcccb0c6-df04-4f56-bd41-15984c7a066d	kugel	6.17	26	weiblich
a3c58a16-3657-4c4e-81e9-7ee123ce4299	kugel	6.23	27	weiblich
00c0dc28-f839-49f7-afb4-96e1ec02ce31	kugel	6.3	28	weiblich
a17d1a8a-a9e1-4014-b9a5-10cce410b7c7	kugel	6.36	29	weiblich
29c5b9ce-8f4d-4de6-a2de-6fdd82cea3dc	kugel	6.43	30	weiblich
4b4c98a9-63e7-45da-8b02-04adec597b4e	kugel	6.49	31	weiblich
3b7a25af-de1c-4ea2-b234-3289009528a6	kugel	6.56	32	weiblich
81740301-95f3-459a-959d-0aa8f3b2dfec	kugel	6.62	33	weiblich
022c9b88-a303-4036-967d-3e329a32950d	kugel	6.69	34	weiblich
5ad3bf9d-a25a-420f-960c-e82be280d7ba	kugel	6.76	35	weiblich
1aad4960-4e4e-42c1-b951-e253f785bd91	kugel	6.82	36	weiblich
51e3a71c-a7cf-452c-ae2d-ff7d670f233d	kugel	6.89	37	weiblich
f81685f5-a21d-424a-abe9-153fa99453e8	kugel	6.96	38	weiblich
8ad89f41-57ad-4b47-9567-f805107f7550	kugel	7.02	39	weiblich
4b82c554-7151-43a9-ad65-d91e7e58c557	kugel	7.09	40	weiblich
f9008a7f-c28e-4497-9764-c3cbb1e9b6c7	kugel	7.16	41	weiblich
0a74007c-c7c6-4225-a895-09f63914912b	kugel	7.23	42	weiblich
109e098b-a9f3-4be9-ae7f-ac37e6cb33a9	kugel	7.3	43	weiblich
0907da19-9e8d-4151-a569-567810685c47	kugel	7.37	44	weiblich
1038e534-c911-47b8-b570-dacd2f1910b4	kugel	7.44	45	weiblich
03d16e7a-6bbd-4944-af1c-73028c578213	kugel	7.51	46	weiblich
82ce11a6-1547-4297-9420-0e538e739d0e	kugel	7.58	47	weiblich
0a1332c4-d064-48b4-a538-129580d153a3	kugel	7.65	48	weiblich
a9a60ab5-b664-4e24-b6fd-8ffbf4b3fc0a	kugel	7.72	49	weiblich
e4840d97-65a0-4db8-9f4d-2b0361df830e	kugel	7.79	50	weiblich
e5999138-a465-4f9d-8293-deb2dab9fdf0	kugel	7.86	51	weiblich
36967fdc-bf08-478d-b7ca-8f625d45f2b7	kugel	7.93	52	weiblich
db32c20c-8681-443b-bd6d-0a13bd3c02c0	kugel	8.010	53	weiblich
90edbc91-b59a-4248-a88c-52a91f7f53f6	kugel	8.08	54	weiblich
c7122640-3606-46ba-8dc0-faecd1791fd5	kugel	8.15	55	weiblich
9a049c2c-15a5-4500-9ecf-dcd23f3afe59	kugel	8.22	56	weiblich
53e9f2ad-a9fc-484e-9e15-cc30c9be4bb8	kugel	8.3	57	weiblich
612393c4-7f0b-4928-91f1-55a7e648623d	kugel	8.37	58	weiblich
e544dbfa-ce91-4f92-8545-e84828328bcb	kugel	8.40	59	weiblich
e79af06a-02a8-483f-9d3e-c9491634b2ae	kugel	8.52	60	weiblich
6424b188-fdc5-48d4-a044-417e994953dc	kugel	8.6	61	weiblich
c6d38ff4-a470-407b-ab37-a38391b9d039	kugel	8.67	62	weiblich
9686296d-b876-46be-be6c-1f3e328626f7	kugel	8.75	63	weiblich
72cdfff3-ccf2-4e9d-b3c6-c98b01e88e0a	kugel	8.82	64	weiblich
834bb462-773f-4ed8-889c-835b041ffd0f	kugel	8.9	65	weiblich
672ab904-8931-4cc6-9de9-ce8f324ceb8a	kugel	8.97	66	weiblich
5b2ec56a-c7ad-4c8d-8024-3886803e7609	kugel	9.05	67	weiblich
fa2e13f4-2776-42a8-a4ca-de25d560625a	kugel	9.13	68	weiblich
4205b2cb-e2d5-4841-9d0f-d99caa1bffee	kugel	9.21	69	weiblich
e5b6f338-00c2-4ee4-ab8f-b0a601647443	kugel	9.28	70	weiblich
616deb9c-d24f-42ff-a5b5-5b34c7cdc8ea	kugel	9.36	71	weiblich
8c60898b-54a5-436b-9d85-17e26c932d55	kugel	9.44	72	weiblich
75b39c2d-5259-4789-a550-ebfa5840c1af	kugel	9.52	73	weiblich
b5893817-5bc5-4be8-8c7c-025041a212c1	kugel	9.6	74	weiblich
24610f78-fba7-4d85-a5c8-84c5c98a304a	kugel	9.68	75	weiblich
ad5b78cc-7d0a-4698-8e84-93fffcb9b209	kugel	9.76	76	weiblich
a6cb431f-1cea-4203-b086-8951ff38d4d9	kugel	9.84	77	weiblich
7e5ef0a8-2f9f-4b3d-b2e5-1837227018cb	kugel	9.92	78	weiblich
e670f2d1-14de-4df3-9673-d744d32f5692	kugel	10	79	weiblich
f52e6a30-df87-40cd-9a9f-c88b19ca6a5b	kugel	10.08	80	weiblich
4ed35c4f-8638-40f0-ba86-445a94a3fd4c	kugel	10.16	81	weiblich
94f37957-2a6f-4c42-b358-8a850b2f4921	kugel	10.24	82	weiblich
5de92660-95c3-486d-9bf6-662565dbaf7a	kugel	10.33	83	weiblich
6cad8c60-bf38-4e79-85e1-65ba92cd68a9	kugel	10.41	84	weiblich
090c6ad4-9c8a-4d09-9a1d-4031f0bc86ab	kugel	10.49	85	weiblich
fb252322-346a-4aa5-abc1-cf8a378695ed	kugel	10.57	86	weiblich
10006be1-c84f-42b3-8807-0ef1f891b9f6	kugel	10.66	87	weiblich
00afaaa7-8b44-458d-91f4-079a03fa8051	kugel	10.74	88	weiblich
dc6db017-6c06-4e2b-b1d5-471008087a07	kugel	10.82	89	weiblich
f6c5481c-dcdf-4711-990e-11ab3492fc83	kugel	10.91	90	weiblich
33265791-2ebf-4617-aede-b5cab2f28de2	kugel	10.99	91	weiblich
9f0621b2-d9cf-4276-90e7-43e3fd527aa6	kugel	11.08	92	weiblich
7743af26-d56f-4f04-9a5c-770c6de1b59d	kugel	11.36	93	weiblich
1c1f5515-edab-463e-8cfe-52ff6d306915	kugel	11.25	94	weiblich
7b44790a-01f6-4a3b-803e-32a8c3890fec	kugel	11.34	95	weiblich
5dbb1bfe-1ab8-427e-938c-807067b10d68	kugel	11.42	96	weiblich
482eae4c-c035-494c-b74d-a5aa2d163a85	kugel	11.51	97	weiblich
ac51b4b7-05c1-4378-9856-68d6c7373fc7	kugel	11.6	98	weiblich
049ee23c-7a43-4a16-867a-18e9e839e382	kugel	11.68	99	weiblich
cca07a2a-d3c8-4774-b1e0-0aa9d5f11399	kugel	11.77	100	weiblich
1dbe99b3-5a41-4306-8a49-36ee0c1a2558	80m	15.21	1	weiblich
b8bb13e2-32ed-48e7-aaf1-b5068437c5ec	80m	15.12	2	weiblich
1be1b945-3c49-4e63-9488-c688f9f3b249	80m	15.02	3	weiblich
902cf10d-bf18-4c09-b055-c044304cff72	80m	14.93	4	weiblich
14e4884b-12f9-4e5e-8f13-7bac8f95e64c	80m	14.84	5	weiblich
aec58782-ef6c-434f-b602-57a348bd7a5e	80m	14.75	6	weiblich
7060ec4b-c9aa-423e-9956-e35df6e2563d	80m	14.66	7	weiblich
7ee8cabf-4bf5-4a0e-9b4e-e5cffcff6523	80m	14.57	8	weiblich
3fb91c36-cb0b-456c-82be-368a0071d2b7	80m	14.48	9	weiblich
ce128591-b907-4e6d-b8e9-1a509e14eac0	80m	14.4	10	weiblich
ba522b7e-40d1-4cc6-bdd1-481f9fb6693b	80m	14.31	11	weiblich
a56c4727-9b74-4e0a-967d-c7dce7826977	80m	14.23	12	weiblich
c6b8431d-ea7e-43c9-a003-3ba401282158	80m	14.14	13	weiblich
12b9bb4e-e12c-4a2d-8de0-92b989b93c53	80m	14.06	14	weiblich
de5dbd49-e29b-429a-8f7c-dd83641730c0	80m	13.98	15	weiblich
0e699cba-9f42-4c98-95fd-74feb48f43ee	80m	13.9	16	weiblich
ee8b7e83-dde9-44a1-8580-8e567b7097a5	80m	13.82	17	weiblich
a6a47b47-5956-4cb1-b872-d0c3409771db	80m	13.74	18	weiblich
d52b7076-3b80-49fc-b77f-faf5943bda34	80m	13.66	19	weiblich
6a237ebd-e717-4021-9e81-c9df6de83317	80m	13.58	20	weiblich
03af5b90-393a-4c8e-8e83-c2bcadd57556	80m	13.51	21	weiblich
3435c0f7-a4bd-4b96-9c62-f58ce5cd8be9	80m	13.43	22	weiblich
69f970ef-20ff-4795-b4c0-c327ea8ddeff	80m	13.36	23	weiblich
5818ac5c-9d5d-4f42-8817-4c7b2d412870	80m	13.28	24	weiblich
7cd932ba-bc13-4137-99b9-e795671e4d6a	80m	13.21	25	weiblich
3b2df93d-1e7e-4032-81de-bdf7e6de458a	80m	13.14	26	weiblich
27604ce5-e4bc-4b2b-ad9d-34d4f7acd363	80m	13.07	27	weiblich
1f693abd-88b0-40c0-b1d8-189c1592aa4d	80m	13	28	weiblich
db7313e4-e03c-4f99-996b-0717a65c46e9	80m	12.93	29	weiblich
32c0d67e-02ee-4f28-87b5-264920451f2c	80m	12.86	30	weiblich
5c9795f7-df40-4226-a3ba-2d2bc1e4c330	80m	12.79	31	weiblich
c1447db0-bfcd-420a-809d-7dd6cd6ec41d	80m	12.72	32	weiblich
671a40ac-d344-4c70-988f-da671cf41555	80m	12.66	33	weiblich
a82c9917-84c2-431e-853e-9b391da16aee	80m	12.59	34	weiblich
34e083c7-14ca-4975-bdb5-328e499a1967	80m	12.52	35	weiblich
e8e23d4d-ea86-4917-9738-b5d534239e1e	80m	12.46	36	weiblich
e44c73f0-c5c4-4eba-ab33-07a7af7b2eff	80m	12.39	37	weiblich
02abbcba-3c0b-4dad-9510-48c168deef24	80m	12.33	38	weiblich
7ea31183-a12a-4eb8-b0cf-64fb0c62ebb8	80m	12.27	39	weiblich
86e069b2-5eef-4567-9660-d421ef1bcb13	80m	12.21	40	weiblich
a79e7fee-15e1-4566-8559-4fd5feda7840	80m	12.14	41	weiblich
ca0b1a79-3692-4196-871a-9ef30bde6ae5	80m	12.08	42	weiblich
c66be956-1310-4dec-b605-1d6bfff01f94	80m	12.02	43	weiblich
3f229986-403d-4ed2-873a-1ab21ddd538c	80m	11.96	44	weiblich
caf4696a-7cb3-447b-99af-39a44757e4a4	80m	11.9	45	weiblich
b7f36fd5-d470-427e-9e13-bb6e609aae39	80m	11.85	46	weiblich
a49abc8d-94b1-4d6a-a291-ff29db7c9fc0	80m	11.79	47	weiblich
7ef851c4-e942-45d8-8180-b1eb0aeb2d16	80m	11.73	48	weiblich
f943760e-5748-41b1-a93c-7ef2ca741626	80m	11.67	49	weiblich
66d9984c-021d-4766-ad9f-908bb6c40fcb	80m	11.62	50	weiblich
a75609fd-0897-4a1d-90b9-72cb21b0ff2a	80m	11.56	51	weiblich
4ee9ceb3-754c-4f8b-b57b-0ad97aebe8d8	80m	11.51	52	weiblich
8ce27699-93b9-4568-956b-a7368069357b	80m	11.45	53	weiblich
403edd31-b8d5-4c2f-8a39-efd2e03d8fa2	80m	11.4	54	weiblich
bc96a440-0701-42b5-8ae3-f0480fe59ef6	80m	11.34	55	weiblich
9b3acb94-2a3a-4d78-a667-3aa42e1fdf06	80m	11.29	56	weiblich
734d182a-907c-4345-aaf8-ebd5c82afd3e	80m	11.24	57	weiblich
69759f5f-f86e-4bc7-bc71-fbb174a4f5f4	80m	11.19	58	weiblich
19bd474b-e229-4e48-9170-8466002f5078	80m	11.13	59	weiblich
c2a5c7e2-7274-4f55-9840-d0c7936aed5f	80m	11.08	60	weiblich
cb6bbf00-dd4a-4a97-a31a-226f80e56339	80m	11.03	61	weiblich
8bf2b810-4592-455a-a9ed-0e96a1650ffa	80m	10.98	62	weiblich
8432e0c4-a382-4df6-85a1-293aeeb3c266	80m	10.93	63	weiblich
d6eb795d-b587-4c0f-8dd0-5ad8e753c2a6	80m	10.88	64	weiblich
384e4515-75ee-4d9f-81a8-2198429b4e33	80m	10.83	65	weiblich
48a6f86d-6d06-472a-a99b-81f677c4d935	80m	10.78	66	weiblich
08d27ffe-1cbf-41e2-ad91-fbdeff277237	80m	10.74	67	weiblich
1e58d3f7-9f39-46aa-8a60-7729539ea041	80m	10.69	68	weiblich
e04afe63-4eb9-4f8a-96c9-d4b5918b2c4f	80m	10.64	69	weiblich
a4409148-b3ac-4021-a73c-e738ed399c97	80m	10.59	70	weiblich
7fea983b-820c-43ce-9aca-5734dde7693d	80m	10.5	71	weiblich
79e3c15e-042f-48f1-a0dc-54fc62ef5d44	80m	10.5	72	weiblich
af2a94e5-3467-4655-ab0d-49deab6d50f2	80m	10.46	73	weiblich
991320fc-1f66-445a-9ace-09797cffa20d	80m	10.41	74	weiblich
0d8bd00b-182c-468d-b910-507f87822931	80m	10.37	75	weiblich
397261e1-39f9-41a9-873a-9b9f4c3bfb2d	80m	10.32	76	weiblich
6f5f4a4b-7298-4773-a797-3e9f530ebf33	80m	10.28	77	weiblich
64aea1df-d8ba-48f2-b698-b7a0f2763b0b	80m	10.23	78	weiblich
19e28024-8d5c-4638-bd00-6ba1ea3f89c1	80m	10.19	79	weiblich
d5a2d48c-2501-41e5-a31f-d236b4eb8634	80m	10.15	80	weiblich
23130391-4b52-46e7-9903-77e9f837812b	80m	10.11	81	weiblich
5d94e854-8a04-4478-8956-59686e4b0636	80m	10.06	82	weiblich
595eee5a-1124-4870-9a6e-fa0efa517e9f	80m	10.02	83	weiblich
f502450a-97a0-4521-a871-04cb548bea86	80m	9.98	84	weiblich
55f4bf50-2e78-4db6-8386-2d2fe592ef5d	80m	9.94	85	weiblich
030ad80c-94d5-4aa7-bc65-21b22f7c4f16	80m	9.9	86	weiblich
674a7437-f91d-49d9-bff9-030ac57456b4	80m	9.86	87	weiblich
af17260c-6dd1-4f6f-a1e3-8f8182f13529	80m	9.82	88	weiblich
f792924c-95fe-445a-bbfb-edb7dd4b632c	80m	9.78	89	weiblich
14e71696-3043-4f4d-9531-104ce80eb2de	80m	9.7	90	weiblich
8bea9f45-90df-4607-be43-570a568181cc	80m	9.7	91	weiblich
0a9b3a34-1b04-451b-9aa4-66055f2c01dd	80m	9.66	92	weiblich
e0bef7cc-670e-43c1-9801-60bded97e976	80m	9.62	93	weiblich
c237c720-dc35-44aa-8a84-addc593c1a4d	80m	9.58	94	weiblich
ba2bff0b-ef8c-497b-b3d9-107df318954d	80m	9.54	95	weiblich
c814cea6-5a50-4359-95d5-b7af9570dee1	80m	9.51	96	weiblich
4f8b6436-edb0-4ce5-99a6-09a94b0f05d2	80m	9.47	97	weiblich
969149c9-ba0a-424c-9f98-4d4a99b05d49	80m	9.43	98	weiblich
d6ae00a0-f863-4ed0-8ee1-af5b9d04f4cf	80m	9.4	99	weiblich
f51c9a2a-2b38-40ba-a218-3bcf0ef5fc1a	80m	9.36	100	weiblich
75eb5b61-eaa0-4d2a-aa27-b3d12bc2d11b	huerdenlauf	22.8	1	weiblich
4d55d943-67cc-4432-95fb-902a707f8f37	huerdenlauf	22.57	2	weiblich
890d26f4-c36c-4f72-99b9-6611e35e9c00	huerdenlauf	22.32	3	weiblich
3881e563-2dc9-4dee-a7d4-b3e6cab39aad	huerdenlauf	22.08	4	weiblich
2a98aa5d-ef01-4088-8828-d71bcee4203f	huerdenlauf	21.84	5	weiblich
35519d99-b34a-4454-9aaf-faba70756e78	huerdenlauf	21.61	6	weiblich
bcea8690-9db0-404c-a422-1cc01e353ead	huerdenlauf	21.39	7	weiblich
ecd10a41-acef-4287-8df7-dea25ffcf1ff	huerdenlauf	21.16	8	weiblich
aa8d02d5-702e-4e4f-b978-4f8c4d4caff5	huerdenlauf	20.95	9	weiblich
5618fb7c-e3b5-4ec9-a6b0-7e1323bf9215	huerdenlauf	20.74	10	weiblich
d14f1d07-038e-49d1-a357-72f1979fd437	huerdenlauf	20.53	11	weiblich
29267b48-75a1-4b9e-81fa-de1e5390ef7a	huerdenlauf	20.32	12	weiblich
631d5ce1-13ce-4151-bdc4-80e98a2c7caf	huerdenlauf	20.12	13	weiblich
09adda6d-9fc9-44be-8633-b4c253b80abe	huerdenlauf	19.93	14	weiblich
f0e0f2eb-2750-4852-a3cb-4f5a2e7bef36	huerdenlauf	19.73	15	weiblich
9387994b-54a1-4945-97bc-8d146922e146	huerdenlauf	19.55	16	weiblich
b3f2e0a6-e5ab-4f16-9f62-4250cff3f486	huerdenlauf	19.36	17	weiblich
a5c4e670-a811-4ca0-add0-08a42895db31	huerdenlauf	19.18	18	weiblich
9aa1e838-8b06-42fc-9e32-7cc0e4e23563	huerdenlauf	19	19	weiblich
09b28ea4-ef35-4ff1-8661-7c1758a95cc1	huerdenlauf	18.83	20	weiblich
5fa5beee-fa6f-44d0-8a33-5a50699c5ded	huerdenlauf	18.65	21	weiblich
10266a88-1db0-43f8-beca-8fe52ad2d0aa	huerdenlauf	18.49	22	weiblich
fbd4ec01-344e-4588-a503-d2fe4a267d83	huerdenlauf	18.32	23	weiblich
2301e6b8-3dfe-4ccb-8a59-aa8b285e1568	huerdenlauf	18.16	24	weiblich
1312f39f-9c8c-4742-b1bd-73e57bd4a2f0	huerdenlauf	18	25	weiblich
303c61d7-73e9-40b1-be6e-135474e40c17	huerdenlauf	17.84	26	weiblich
4d10e576-51e3-4d42-b8c4-b2cd78c5a3ee	huerdenlauf	17.69	27	weiblich
d369c2d7-a31d-4fad-8b89-7f176c7d095c	huerdenlauf	17.54	28	weiblich
0dc0e67d-f515-4296-9733-a552e93195ea	huerdenlauf	17.39	29	weiblich
5c32ce50-9119-48af-849c-248e60dee619	huerdenlauf	17.24	30	weiblich
49d5a1c2-f924-4e9a-864c-651da73299dc	huerdenlauf	17.1	31	weiblich
1b5b0f5a-4549-48fd-b913-d29dfbfe6d19	huerdenlauf	16.95	32	weiblich
ce329555-6b3c-43ed-ac1a-2d9689e1a026	huerdenlauf	16.81	33	weiblich
90d88633-46bd-4368-a475-5669f9ed0077	huerdenlauf	16.68	34	weiblich
30214210-ceda-4d7e-8e76-e91188387d83	huerdenlauf	16.54	35	weiblich
fab5ae77-085f-445d-9977-8318386d4d6b	hoch	0.97	2	maennlich
e3a4aedb-36c8-4664-9b64-21df39f10ba9	hoch	0.98	3	maennlich
87b9a81e-a62d-4564-912e-656e886edf36	huerdenlauf	16.41	36	weiblich
a13cd50a-2587-429d-b065-65c18c06b632	huerdenlauf	16.28	37	weiblich
e36b37ce-bc6a-4fea-a4be-0595e878612d	huerdenlauf	16.15	38	weiblich
7a8c9093-513c-4f4b-bd47-a6d175f98091	huerdenlauf	16.02	39	weiblich
a01682b5-88f7-4e3b-91ce-5bbec50c879f	huerdenlauf	15.9	40	weiblich
0b594c55-0184-4f28-878a-6d2b4c29b297	huerdenlauf	15.78	41	weiblich
2d08cde4-e789-4401-8d3d-c2b45d27512a	huerdenlauf	15.66	42	weiblich
35f978b0-d7b9-49de-8b0d-ac0db0fd6aee	huerdenlauf	15.54	43	weiblich
d4d0bdcb-f8fe-41c9-80ef-48520be6a3cf	huerdenlauf	15.42	44	weiblich
1f3d0bdc-dcf2-41ca-a812-3211246f349a	huerdenlauf	15.3	45	weiblich
224af7b9-ba49-4802-81eb-5209dcc0da03	huerdenlauf	15.19	46	weiblich
40babaab-efcd-4f8d-ba4f-cd15fdf31416	speer	6.03	1	maennlich
3227f74a-4b98-40bc-b43b-89034fa80afc	speer	6.36	2	maennlich
fadfdf8e-ed27-40f3-bf5d-6456556a15d5	speer	6.69	3	maennlich
293a7d84-e4e2-459f-b61d-7658df16c18b	speer	7.02	4	maennlich
c8d59478-b6a8-42ec-9653-325620b9def6	speer	7.36	5	maennlich
0f2af48b-7eea-4b2a-9011-f623f2f37612	speer	7.71	6	maennlich
ec5d960b-c128-4d5c-b2ca-cf005440d3e4	speer	8.06	7	maennlich
a8947ca3-182e-4a20-b72c-49b25d2ba3c3	speer	8.41	8	maennlich
c7fb1deb-6dc7-40e1-824f-f4745686ef0a	speer	8.77	9	maennlich
447aa919-d186-4d34-837e-8a76b7f746e7	speer	9.13	10	maennlich
b5112645-a2de-4beb-b41d-2ae6954241fb	speer	9.5	11	maennlich
fe3b1507-aad3-4c9c-9ed4-161c08ce3d85	speer	9.88	12	maennlich
37934a31-a56f-4d65-94cf-b7d8665d63f4	speer	10.25	13	maennlich
7c84178e-1eb4-4378-a370-1626e277474f	speer	10.64	14	maennlich
d7d59250-772d-46e7-9b16-4ea37d6b8473	speer	11.02	15	maennlich
4747b78b-4e25-4d7d-9ab4-09f11e6e811f	speer	11.42	16	maennlich
13c3b7a7-d61b-4bca-a313-4005cfae76d5	speer	11.81	17	maennlich
2d6306fe-fff8-4409-ba77-fffa37307dca	speer	12.22	18	maennlich
92036bf7-9940-446c-a506-3f29e7542422	huerdenlauf	15.08	47	weiblich
388b1866-3139-4331-84c6-7cd624950d69	huerdenlauf	14.97	48	weiblich
67f75fe5-71c8-4b2e-92b3-1fbf899d6886	huerdenlauf	14.86	49	weiblich
fb740edd-31c4-4826-92df-3bd58e0c298d	huerdenlauf	14.75	50	weiblich
061fb533-70c3-4194-8986-99e6c49a662d	huerdenlauf	14.65	51	weiblich
c824ff96-c545-47fe-aa7e-abffbabec30a	huerdenlauf	14.54	52	weiblich
79f27585-78c1-48d9-945a-aa043000c9e3	huerdenlauf	14.44	53	weiblich
742e2f6a-e13d-4df6-8514-0e56fa75a661	huerdenlauf	14.34	54	weiblich
e91b7ae5-38d6-4145-a080-e963e9e7e958	huerdenlauf	14.24	55	weiblich
6616fc0e-e856-4920-b4b9-a90ef1b27e90	huerdenlauf	14.14	56	weiblich
87eed019-a8f5-4b57-bf7a-19c6801504b2	huerdenlauf	14.04	57	weiblich
1f72ba90-34f0-4662-a71f-2e97d7cb1dc5	huerdenlauf	13.95	58	weiblich
d1a7cce1-be2f-4987-b821-6fd52d10133f	huerdenlauf	13.85	59	weiblich
546eae4b-29d1-41e4-aff2-b6fd8147aa54	huerdenlauf	13.76	60	weiblich
1afc8bdf-0691-4773-9f5c-8df4d1547f04	huerdenlauf	13.67	61	weiblich
2f2813ae-3977-409c-9907-157d878f5f41	huerdenlauf	13.58	62	weiblich
6d7cf938-66da-437d-83d4-565b10f033d4	huerdenlauf	13.49	63	weiblich
769de079-92a0-44d2-b4d2-1cda8a552d23	huerdenlauf	13.4	64	weiblich
40c00237-a03f-4a4d-9901-531dd52e1182	huerdenlauf	13.31	65	weiblich
eb4bc5d4-dc97-4421-b91c-1d678b608383	huerdenlauf	13.23	66	weiblich
2e97e79c-f847-4559-b2f1-0d8d7f4ce8c3	huerdenlauf	13.14	67	weiblich
da37bdd7-38a6-4512-8f7c-c4c414e46679	huerdenlauf	13.06	68	weiblich
063bb45e-99c9-4dd3-9f6e-b403485cbfec	huerdenlauf	12.97	69	weiblich
2b23aba6-5648-469c-ba50-b4e12fb182a5	huerdenlauf	12.89	70	weiblich
cc55f116-25d2-4ea4-9569-37091d284b27	huerdenlauf	12.81	71	weiblich
12dfa10a-3a72-4fc9-96ac-95fbcc305da6	huerdenlauf	12.73	72	weiblich
f4a0c17d-2a01-47db-9d40-5f38afff8903	huerdenlauf	12.65	73	weiblich
5aae6596-3f17-44eb-832f-3a8fc0365e27	huerdenlauf	12.57	74	weiblich
54ab6673-740c-43ae-be8d-8462230ef136	huerdenlauf	12.5	75	weiblich
876802c8-00bd-4fef-a3af-c03387b3688d	huerdenlauf	12.42	76	weiblich
14654c81-73c2-4e7b-b75e-04b77fa2a147	huerdenlauf	12.35	77	weiblich
3a5cf092-d4c0-4d12-ae90-6bdb63ca32be	huerdenlauf	12.27	78	weiblich
be8e1fe2-a9d8-4ea0-989a-031f904de141	huerdenlauf	12.2	79	weiblich
3fe0ca05-922e-4954-875c-69dd38fec476	huerdenlauf	12.13	80	weiblich
4c430c31-b6c5-4010-8d8f-cac453a85e1b	huerdenlauf	12.06	81	weiblich
8918fc76-7afd-4ef5-8069-ed85fbc83438	huerdenlauf	11.98	82	weiblich
06a015a2-4dcd-40fe-8abe-2cce8bb94d6a	huerdenlauf	11.91	83	weiblich
5b60e00d-454d-4e16-bbae-d2cf3387c965	huerdenlauf	11.85	84	weiblich
97df9082-3fe6-49b7-a160-80d3893a6695	huerdenlauf	11.78	85	weiblich
7a3e9c15-46ea-4580-8061-ef25874ac903	huerdenlauf	11.71	86	weiblich
c5c66eff-5466-4bd9-9527-01fbdfc86875	huerdenlauf	11.64	87	weiblich
5c3bda7d-37b2-4cd8-90ee-e96a2033e27e	huerdenlauf	11.58	88	weiblich
58592184-9768-43a4-91bf-7d46239dc900	huerdenlauf	11.51	89	weiblich
8d30d829-cadb-473e-9322-3fd0396c49ef	huerdenlauf	11.45	90	weiblich
8fb600aa-f8cd-4dfd-a547-8d50ee897c5f	huerdenlauf	11.38	91	weiblich
387c9c80-6a79-4c3b-842e-a8b43704437c	huerdenlauf	11.32	92	weiblich
11bcde87-64a5-4454-8f10-6f04a76a1eb0	huerdenlauf	11.26	93	weiblich
92a94a15-56a9-4b76-aca0-a35cfc105f8d	huerdenlauf	11.2	94	weiblich
5a9623bc-0038-4268-b823-28ca0023b1a3	huerdenlauf	11.14	95	weiblich
c633553a-70df-4cae-bb68-960f8569a390	huerdenlauf	11.08	96	weiblich
895ff4cf-02c5-45b7-860a-1bc108ac17d1	huerdenlauf	11.02	97	weiblich
2dfd32f7-4ff7-46ea-992d-ba50863c5384	huerdenlauf	10.96	98	weiblich
1e180028-9b11-4322-b98a-ddff9e24d660	huerdenlauf	10.9	99	weiblich
2207c591-5bbd-4c12-9d20-2d2fc7b8ef35	huerdenlauf	10.84	100	weiblich
d1c9dfb2-ddb6-40dd-b4d3-e282f1e15e62	huerdenlauf	11.8	54	maennlich
79a15c08-2a11-46ad-9cc9-861660799575	huerdenlauf	11.75	55	maennlich
d3d9b1eb-1bf1-4f41-8c2f-d451af898df9	huerdenlauf	11.69	56	maennlich
4550bc19-d759-4870-8b3d-00903c26b9e2	huerdenlauf	11.64	57	maennlich
7a2d76f3-7491-43e7-b756-84b13329851b	huerdenlauf	11.59	58	maennlich
dda4b553-cea2-4694-b988-a49d310b6487	huerdenlauf	11.54	59	maennlich
ebbe4e77-c4b5-4064-8b2c-247a126f0276	huerdenlauf	11.49	60	maennlich
7c679345-3353-457f-bd89-f9612525ac8a	huerdenlauf	11.44	61	maennlich
155b8998-52dc-408c-8833-b28a68d7a9e3	huerdenlauf	11.39	62	maennlich
d994c0ea-cdb6-4a76-a956-b839ca416a25	huerdenlauf	11.34	63	maennlich
a0b3125e-3b9c-448e-9148-e36edee5e02f	huerdenlauf	11.29	64	maennlich
02ebfbde-5bfa-4c32-a9fc-81d02838e2b5	huerdenlauf	11.24	65	maennlich
e433cc09-e91e-45c4-956e-8396c52417fb	huerdenlauf	11.19	66	maennlich
0520cd11-1356-41e7-bed2-824471f76302	huerdenlauf	11.14	67	maennlich
9d6cf06e-7c5d-4e28-bc35-8b552fb615fd	huerdenlauf	11.1	68	maennlich
7453cf69-754c-42a7-a2b3-2695426194fd	huerdenlauf	11.05	69	maennlich
476cdfdd-1721-4e65-8526-54f463b64cdb	huerdenlauf	11	70	maennlich
57ea4887-0f9a-4010-adf6-180a72e9fd21	huerdenlauf	10.96	71	maennlich
edd405cf-cef8-4ca7-9587-c28077824a94	huerdenlauf	10.91	72	maennlich
a9d830ea-6383-46be-a833-9f9b6438feb3	huerdenlauf	10.87	73	maennlich
9fc39d4a-e2db-4e82-898b-fd4e89c423a3	huerdenlauf	10.82	74	maennlich
fdea021d-8d35-449d-9e1a-15ede8604229	huerdenlauf	10.78	75	maennlich
b569c568-863a-4e62-bd04-a687c01ae3b4	huerdenlauf	10.73	76	maennlich
69e011fd-b27e-4484-88aa-099871801468	huerdenlauf	10.69	77	maennlich
b27cb43d-b64a-47d3-9433-8ce9ded65349	huerdenlauf	10.64	78	maennlich
e818a498-dc53-4cbf-8e48-a9e91ae08671	huerdenlauf	10.6	79	maennlich
bc3ef947-265c-447e-96b3-24cb0121e2fa	kugel	4.46	1	maennlich
d45c9b98-fa55-4fad-865a-b93269c3e00b	kugel	4.54	2	maennlich
eaf35d4b-f54a-47ca-b766-248607ea0707	kugel	4.62	3	maennlich
eb0f249e-79ba-4251-b5a9-783543eddc68	kugel	4.71	4	maennlich
52a7180e-d831-4b81-989c-787a707c470f	kugel	4.79	5	maennlich
c22ebf77-e58c-47e7-96fd-0dfd81de4ed9	kugel	4.88	6	maennlich
c9de173d-af0c-4aea-aba3-21e07094b2b9	kugel	4.96	7	maennlich
51e47bbf-4850-466e-af34-997989c5b314	kugel	5.05	8	maennlich
bbee79ae-b1e2-46b3-a100-897e1da445dd	kugel	5.14	9	maennlich
77f84c93-5398-43e1-ab77-4c4d1b558f07	kugel	5.22	10	maennlich
f7e4e7bf-0384-4221-b476-81f419cf02a6	kugel	5.31	11	maennlich
858934bd-acd0-4321-834a-d4e556db802c	kugel	5.4	12	maennlich
7f023ea0-fe25-4698-a720-8a6f9379c3f1	kugel	5.49	13	maennlich
b0b5538e-f3c1-462e-b906-0d5f212ea080	kugel	5.59	14	maennlich
88feb836-b60f-4012-af79-52ae8122dfda	kugel	5.68	15	maennlich
5842a01c-5a66-4c05-a0fb-5282a05f4cd1	kugel	5.77	16	maennlich
641cb30a-8a96-4ae4-9d02-7dbb610016f5	kugel	5.86	17	maennlich
fc2b80b2-baec-43ee-ac91-696260fc4348	kugel	5.96	18	maennlich
29b4fb23-37f3-4caa-8835-7bc8aa09fa96	kugel	6.05	19	maennlich
dc7ad2c4-0d57-4d98-a477-2fb9e6e3a46a	kugel	6.15	20	maennlich
916a3670-af4d-4a12-b844-c382fbc7d54e	huerdenlauf	10.56	80	maennlich
b172f74a-81d4-480d-95b7-322544306659	huerdenlauf	10.51	81	maennlich
8726470c-3bff-4deb-a6c1-d2b56e961da9	huerdenlauf	10.47	82	maennlich
39bace71-c4d4-498e-b3ed-3d63cbee4800	huerdenlauf	10.43	83	maennlich
e91251d3-c051-4fed-b6c2-554f4fcd5415	huerdenlauf	10.39	84	maennlich
063281c8-9ba9-4b96-b049-cd4be7468993	huerdenlauf	10.35	85	maennlich
73f88063-90b8-4b49-87a6-d7f4943e814e	huerdenlauf	10.31	86	maennlich
4deb2cbd-23bb-4b8a-8b7e-2b3f68be53d8	huerdenlauf	10.27	87	maennlich
faca9fc1-7df8-4b11-a0d6-5c94acadf825	huerdenlauf	10.23	88	maennlich
6dbdd25e-6933-481d-bc46-575d2cde8e72	huerdenlauf	10.19	89	maennlich
6a2f9486-2a34-4807-8d3d-42e1d38e4f69	huerdenlauf	10.15	90	maennlich
807a1b6e-9a08-4355-8cfe-b8730b8c743d	huerdenlauf	10.11	91	maennlich
e49ce105-c131-4003-a123-aebaab3a907b	huerdenlauf	10.07	92	maennlich
08d9b320-cea6-48a4-9d12-fb382fcde068	huerdenlauf	10.03	93	maennlich
c5732bac-8c4c-4dfa-966e-920a1a72208a	huerdenlauf	9.99	94	maennlich
5298dbae-4e30-4ff9-8d88-2889091f51c3	huerdenlauf	9.95	95	maennlich
8a1c1a09-ddd8-48a0-ba0f-7a73f43276b3	huerdenlauf	9.91	96	maennlich
8cf2e4a7-8a41-4518-bc62-b03d7d929a56	huerdenlauf	9.88	97	maennlich
45f5ce42-485e-43f4-98b9-605a85e1776b	huerdenlauf	9.84	98	maennlich
5eade1ed-a2f1-49a9-8245-62f31a2b39c8	huerdenlauf	9.8	99	maennlich
403923c6-a7dd-42ea-aaa5-b764e37ab144	huerdenlauf	9.77	100	maennlich
c94061c7-a370-4b0d-967a-a7ba1031bbe6	huerdenlauf	11.91	52	maennlich
64b80f37-8ff6-4698-b767-28f1a161d525	huerdenlauf	11.85	53	maennlich
3eecfa70-0225-4dba-8481-1f9b7efe37ce	huerdenlauf	15.52	1	maennlich
b9e335d5-02c2-48a0-a73a-943c61708cee	huerdenlauf	15.43	2	maennlich
deaae32b-7a5f-459a-8209-ca93c7ce8ae3	huerdenlauf	15.34	3	maennlich
dea72a9b-5f97-4835-8173-3f4e7b2ea2be	huerdenlauf	15.25	4	maennlich
f5e16002-d62d-4071-aa7e-0f55c36b484e	huerdenlauf	15.16	5	maennlich
496949ea-49b2-4965-a57b-5f0e9c9a131e	huerdenlauf	15.08	6	maennlich
cd6a6e8a-8ddf-4650-9f74-6e881f7addf4	huerdenlauf	14.99	7	maennlich
5a7275c9-27f2-4447-8995-9dac1c6578b5	huerdenlauf	14.9	8	maennlich
444971d4-2111-4e09-b4d7-ac99fa30e260	huerdenlauf	14.82	9	maennlich
70aaa397-f314-457e-abc2-9d3586058989	huerdenlauf	14.74	10	maennlich
22faaf29-13ae-4438-a6c9-a735060ea4a8	huerdenlauf	14.65	11	maennlich
052fe0cf-0126-4826-a4bc-b6388daabb0d	huerdenlauf	14.57	12	maennlich
1f7830f7-dcc6-488f-b134-31b2d80a716c	huerdenlauf	14.49	13	maennlich
26d44696-cd12-4a97-a05b-5aa2b1d17ec1	huerdenlauf	14.41	14	maennlich
38dcb816-f960-45e2-bf16-2d961aedff8d	huerdenlauf	14.33	15	maennlich
a1f4cf74-c25e-4462-a276-feea9f3c0367	huerdenlauf	14.25	16	maennlich
3f4b6484-a6bc-4420-9b4f-699f3f60486e	huerdenlauf	14.17	17	maennlich
f83ae433-45c3-4286-9c25-b1d9fcb8f134	huerdenlauf	14.1	18	maennlich
fee2e62f-4512-4531-b619-9389b7b6546c	huerdenlauf	14.02	19	maennlich
d1a90e2c-4fb5-4490-984c-8d05c42311c3	huerdenlauf	13.95	20	maennlich
ce7ceec3-877a-4575-9b54-ffb50467aeb4	huerdenlauf	13.87	21	maennlich
5046f2a4-2df3-47eb-accb-07750051c005	huerdenlauf	13.8	22	maennlich
dbbd6f56-a294-433d-9404-dada89a7ea22	huerdenlauf	13.73	23	maennlich
919fb638-3ab5-4919-8623-c3fe08156f0b	huerdenlauf	13.65	24	maennlich
2a232611-c181-4461-a89e-fcecd47e25a0	huerdenlauf	13.58	25	maennlich
cdecb19b-97ef-4a81-88be-de5c0721850b	huerdenlauf	13.51	26	maennlich
3c393637-f26b-4f7f-83cb-e7bf0f9e1fdd	huerdenlauf	13.44	27	maennlich
7e30c810-7538-4c24-8b2c-9e81df19249c	huerdenlauf	13.37	28	maennlich
0e4abf00-7818-4f20-91d2-6c04139fc061	huerdenlauf	13.31	29	maennlich
b19f89f8-72a9-4dfb-9af8-92d135c61809	huerdenlauf	13.24	30	maennlich
8204a6d5-f498-426f-8716-c58cef476129	huerdenlauf	13.17	31	maennlich
3056223b-8826-411e-aa73-adf0b93e404c	huerdenlauf	13.11	32	maennlich
4283ccf2-4bae-4c2f-af0d-05bbd2d205db	huerdenlauf	13.04	33	maennlich
71c2693d-afc0-4053-8988-9778b2431cab	huerdenlauf	12.97	34	maennlich
72df10a1-9e0e-4b7f-a10c-e53b71531694	huerdenlauf	12.91	35	maennlich
007b1e07-6b89-4943-afa7-69dbe4cb202f	huerdenlauf	12.85	36	maennlich
824fec78-0462-4f01-ae15-86a47b2dce6e	huerdenlauf	12.78	37	maennlich
6ab6d928-cb0e-4539-8124-a34748fb9102	huerdenlauf	12.72	38	maennlich
6cd913ec-45d5-4b29-acdc-98c53eeea186	huerdenlauf	12.66	39	maennlich
be759446-618e-4887-8123-df193a96b990	huerdenlauf	12.6	40	maennlich
50fb9e14-60b7-47a4-aa5b-1c8fc2257bb1	huerdenlauf	12.54	41	maennlich
0d98dff8-d211-4e01-a167-92ac9d0c854a	huerdenlauf	12.48	42	maennlich
74a4aaa7-3e70-4e8e-814f-61bb712bcdb7	huerdenlauf	12.42	43	maennlich
4737c28e-58ce-417c-8095-7e6b4f0fccf5	huerdenlauf	12.36	44	maennlich
65064775-0593-484d-8c08-6ba3ce0f9751	huerdenlauf	12.3	45	maennlich
b8291f36-ac36-41d1-ad8c-ffb048fdf34c	huerdenlauf	12.24	46	maennlich
e6ed04d4-7c4b-49b0-a2ae-1e67e7b6a824	huerdenlauf	12.19	47	maennlich
30a5fd74-aad8-4b79-908a-527f35145fd0	huerdenlauf	12.13	48	maennlich
78713119-f696-4d68-98df-86121b7240d0	huerdenlauf	12.07	49	maennlich
617d35e4-7109-4c5f-99b8-0432e73776c3	huerdenlauf	12.02	50	maennlich
c681e33c-0db8-489a-b7bb-bb686c851238	huerdenlauf	11.96	51	maennlich
222fab68-5cae-4d5a-9c69-8da97c3a949a	hoch	0.96	1	maennlich
380acf6a-e89b-4ae4-80ec-9390013e45f9	hoch	0.99	4	maennlich
4ee7bc1c-8201-4f1d-bb98-19edb21bf019	hoch	1	5	maennlich
cc01b0d8-d26d-410a-a170-5aaae640d44c	hoch	1.01	6	maennlich
5105b420-1cf4-4a5a-bc18-251003262ebb	hoch	1.02	7	maennlich
84f4e326-3ace-4685-bc75-4c4d8ac8910c	hoch	1.03	8	maennlich
e650377d-868f-4832-9d3a-909fc3f49ab6	hoch	1.03	9	maennlich
d5a91e9b-e76d-41c3-862e-1b410340f489	hoch	1.04	10	maennlich
ec43287b-2f96-4c89-b01d-4a249e63bfe3	hoch	1.05	11	maennlich
152aa001-d9a4-44b8-94b6-517f31ef0108	hoch	1.06	12	maennlich
2b23a43c-262b-4cdd-abf8-fe28659809af	hoch	1.07	13	maennlich
3aecdb87-4b00-425b-8bcf-46bc2a120095	hoch	1.08	14	maennlich
4c7a6457-a3de-4493-91e9-578ac1ef5b7e	hoch	1.09	15	maennlich
e0a6f5c8-d44b-4397-b651-eecb91a363fd	hoch	1.1	16	maennlich
92875aa1-4731-4a2b-8a3e-8f043eecd1d4	hoch	1.11	17	maennlich
cadb7d16-0c57-4451-855e-3747a9c28fab	hoch	1.12	18	maennlich
4f9c3c50-ac52-497b-88fd-8fa2ab0effd9	hoch	1.13	19	maennlich
ad26b991-d901-4fa1-b56f-9e5fb828e2c6	hoch	1.14	20	maennlich
56bb1a92-71a0-40a8-b795-3025a72123c1	hoch	1.15	21	maennlich
cfb21caa-7c7e-4b84-a060-1c734c794c38	hoch	1.16	22	maennlich
f91cecb1-87dc-48ae-bfce-b8ef1fc40ddd	hoch	1.17	23	maennlich
a326fb7c-e7c8-4fcf-8c86-62d4b3cd5b61	hoch	1.18	24	maennlich
5e694bc5-7ed7-4998-a31f-c6eed2d51529	hoch	1.19	25	maennlich
34bef7f3-2e1a-4006-89c0-ee4150371923	hoch	1.2	26	maennlich
ce5c18f0-fb30-41f3-8c77-85403e81a0cd	hoch	1.21	27	maennlich
41a79268-1bb0-4f08-92e9-9a0045a3866e	hoch	1.22	28	maennlich
8e09dd20-9eb6-4bdd-8ae4-46a0cc967f16	hoch	1.24	29	maennlich
737f1250-ddc5-41b1-8927-476588076993	hoch	1.25	30	maennlich
86297d1a-5611-4bc6-8eaf-b17842a9bff6	hoch	1.26	31	maennlich
3c323162-610d-4555-89f5-2f2360b4fd93	hoch	1.27	32	maennlich
20120d49-83dd-4441-8e85-598957a069c0	hoch	1.28	33	maennlich
d1a690b7-8115-45ad-8051-f57bc8f62416	hoch	1.29	34	maennlich
dba7a91e-0d14-4ce8-ad21-53241e4d7c43	hoch	1.3	35	maennlich
15a2e0c0-a782-4fe7-9749-8b4542fc32ae	hoch	1.31	36	maennlich
42a62668-1abf-4ad9-b987-3361e376ffac	hoch	1.32	37	maennlich
7930830f-bda0-4f65-aeca-056fd88d888d	hoch	1.33	38	maennlich
6b9d06b0-19e7-435a-a995-32d114d99d69	hoch	1.34	39	maennlich
33bcd6b4-a9e9-452b-b009-bda192caf92a	hoch	1.35	40	maennlich
0360f478-041e-451d-8dfa-bff59918f0da	hoch	1.36	41	maennlich
89c8e7a5-29c1-4557-b29d-1c5455e6a017	hoch	1.37	42	maennlich
d01b078d-e6d5-420c-82ef-b2813b5aa450	hoch	1.39	43	maennlich
fde59cf6-4ef0-4191-a100-4cc3dd44a6f8	hoch	1.4	44	maennlich
a835fb52-715b-46bc-ab30-374f58748571	hoch	1.41	45	maennlich
bd9217f7-4ee9-4964-a7bf-b8fea1eab0b1	hoch	1.42	46	maennlich
2587184f-2e55-43d3-b351-ad48b413c1a0	hoch	1.43	47	maennlich
08b04897-50ed-4faf-861b-cdc20ecb1a58	hoch	1.44	48	maennlich
7baa9d6a-5180-4955-8501-8f32f718001e	hoch	1.45	49	maennlich
9d7c1300-a378-4541-bacc-a0c4a7e6ff50	hoch	1.46	50	maennlich
043655cc-274f-4eb3-9fdf-a4709cf3552c	hoch	1.48	51	maennlich
11b2c8fa-4daf-4078-b2e1-60413a17fb48	hoch	1.49	52	maennlich
62181a35-fcb3-42a6-8480-7f851ee30af1	hoch	1.5	53	maennlich
b00d50dc-865d-4f5f-9e2d-63eacb1f81f8	hoch	1.51	54	maennlich
3eb8aca6-3a25-4f02-a9e8-7b59d6226fa1	hoch	1.52	55	maennlich
cd3a3bc8-cd34-439c-ab91-944f680072cf	hoch	1.53	56	maennlich
6b08b200-ea38-438b-9c79-d148b2d25ef7	hoch	1.54	57	maennlich
e0e26e09-2d87-4f40-811e-91b464584c4d	hoch	1.56	58	maennlich
d1a6e202-6229-4d1f-bce8-3cf22d33ea5b	hoch	1.57	59	maennlich
58adb704-a127-413b-a577-9008c582e1d6	hoch	1.58	60	maennlich
0d070ba8-1abc-4bc9-be7f-4c2b641a7803	hoch	1.59	61	maennlich
df74996e-c4dc-4154-b7eb-ec06551b6af5	hoch	1.6	62	maennlich
0c5b6642-9804-4b11-9717-0ada6bc9a548	hoch	1.62	63	maennlich
f9ced77f-5381-40e7-ab3d-c55db271ab62	hoch	1.63	64	maennlich
7fe2df44-3d7d-4b79-992b-e1d2c8416fea	hoch	1.64	65	maennlich
7f014027-d8a8-453d-87e4-1d4d93acad73	hoch	1.65	66	maennlich
bf3be126-8f91-4ac7-9185-eaca9383614f	hoch	1.66	67	maennlich
17ede474-ede6-4928-bf9f-327c35985366	hoch	1.68	68	maennlich
c3d35c00-13ba-4497-a229-50614ced99db	hoch	1.69	69	maennlich
f4475fae-990d-45ce-85b2-10522d824561	hoch	1.7	70	maennlich
c0df37d2-52db-4367-afda-8c1c0e730c4f	hoch	1.71	71	maennlich
280be804-0610-4df3-90b9-14b5be78c964	hoch	1.72	72	maennlich
ad0c2f26-cc06-4f1d-b057-dc83c004df6a	hoch	1.74	73	maennlich
72f59134-d99c-4bc2-bcb7-d6ea7c0c4854	hoch	1.75	74	maennlich
788e437b-a777-4b49-b4ff-3606159cc7b9	hoch	1.76	75	maennlich
6f264e5d-c6e1-4939-8976-c25c8f8f09bd	hoch	1.77	76	maennlich
05348e1c-5017-4e69-bdb3-02a8e1a8e3ba	hoch	1.79	77	maennlich
b4d4e3c2-db6e-4aa6-9391-da96dd10ed0d	hoch	1.8	78	maennlich
c4bb2678-cfd1-450a-8473-96f5743e4960	hoch	1.81	79	maennlich
3879a71a-83b6-415f-94d2-45d6325c20f2	hoch	1.82	80	maennlich
5e569cf2-b0a2-4cf0-b39e-1b0f25fe17e9	hoch	1.84	81	maennlich
4e5ae48a-7c9d-4d34-8003-99dae1101115	hoch	1.85	82	maennlich
c95a1069-a343-4b65-835e-34e1c9d7b4cd	hoch	1.86	83	maennlich
5c4566fd-3306-4986-a627-270669717abf	hoch	1.88	84	maennlich
7ec7c19b-cd70-4d50-b3cb-f41b79d98b2d	hoch	1.89	85	maennlich
85104173-8910-4506-80fa-0d0f5027b6ee	hoch	1.9	86	maennlich
94ced721-b7cb-4890-b64b-2d0ffca6e291	hoch	1.91	87	maennlich
c1e310ff-7cca-4025-9eb1-eeeaf5f772bf	hoch	1.93	88	maennlich
9f43e71c-38cb-43a1-937e-e3ee9034fedc	hoch	1.94	89	maennlich
c4efbdce-1f0d-42e5-a73a-f3ddeb8c6e87	hoch	1.95	90	maennlich
2254551d-8423-4236-a074-1400007aecee	hoch	1.97	91	maennlich
74b2ad2a-d2ff-478e-88b6-bfa01299523d	hoch	1.98	92	maennlich
2c527f6e-8135-462b-829c-9c35489f57d7	hoch	1.99	93	maennlich
395a8a70-b377-44a4-af6c-e0285708e053	hoch	2.01	94	maennlich
e322e428-31e3-4412-a87a-4c08903ab028	hoch	2.02	95	maennlich
e151e15e-f82a-4776-bb86-e65753e090b7	hoch	2.03	96	maennlich
4817bdc5-ff51-4654-bfc2-a23247605cdc	hoch	2.05	97	maennlich
4ed2edce-4e1b-44da-83b2-e7ed8d0d7b01	hoch	2.06	98	maennlich
acfd0cca-d35a-491f-927f-276ed2d6ad03	hoch	2.07	99	maennlich
e8c815c7-bf21-48e5-a164-8081673dd355	hoch	2.09	100	maennlich
8ba5d137-b99e-4991-8c06-f11a65c49e99	hoch	0.95	1	weiblich
4d6fb687-7c0a-4a60-bba2-3258fab240a4	hoch	0.95	2	weiblich
d329d108-c70d-4bfe-9350-d4a878ee52e2	hoch	0.96	3	weiblich
d2dc99e1-7f99-4251-893a-41e966a35d90	hoch	0.97	4	weiblich
b7d4d425-0784-4566-b343-40911d55ccca	hoch	0.98	5	weiblich
e398f176-c616-4467-98c1-067b0ff95ceb	hoch	0.98	6	weiblich
5ba75b43-ae04-434e-8552-f9432ee92d0a	hoch	0.99	7	weiblich
9f298601-6b17-46e3-bb74-141ac9c0ab4d	hoch	1	8	weiblich
d4d39bf3-9851-4452-b7ab-f0a38796f61c	hoch	1	9	weiblich
8847d538-5bab-4975-b610-d1387aa74f17	hoch	1.01	10	weiblich
3e9f817d-3599-477a-8e14-33d6f1aa3a2a	hoch	1.02	11	weiblich
2fff341b-5120-45ac-a278-b2b337fa66c9	hoch	1.03	12	weiblich
d373a8a3-62cb-4c0e-884b-cd9826965166	hoch	1.03	13	weiblich
89d53d50-456c-49f2-a6b6-ce8ef62da8b5	hoch	1.04	14	weiblich
6d1870ec-9382-49fd-a495-d31b4855f303	hoch	1.05	15	weiblich
9fd4a0f8-b3df-428b-b4dc-aef164783859	hoch	1.06	16	weiblich
74edea1b-7289-47d7-aa05-c5756f69223d	hoch	1.06	17	weiblich
1f15a3cb-3945-4797-a37d-7e614fe9b802	hoch	1.07	18	weiblich
f992254f-3f1f-4372-8cc6-38c3990d27a8	hoch	1.08	19	weiblich
beeb3596-6a61-4421-9005-8bdb3e8e9015	hoch	1.09	20	weiblich
65a67166-119e-4472-9c68-cc2bd6b51a96	hoch	1.09	21	weiblich
19afa9b1-bd3c-4bef-b48e-8317d40695b1	hoch	1.1	22	weiblich
329570f2-3807-4842-8953-67c6e39b887f	hoch	1.11	23	weiblich
22dcccbc-c069-4e02-b252-30788c43dc2e	hoch	1.12	24	weiblich
96c93360-afe9-4fa4-9e1f-4e27acf2d24c	hoch	1.12	25	weiblich
acbb8c79-514a-48b8-a16f-7f554e6f5da5	hoch	1.13	26	weiblich
765b1461-a485-475f-a272-42d7d1f00724	hoch	1.14	27	weiblich
03a16b93-2cc3-4448-94e8-52e3bc6a09ce	hoch	1.15	28	weiblich
f26a15b7-a996-4782-a21e-455f5be022cd	hoch	1.15	29	weiblich
e1cd76ba-c782-43d4-81f5-bd56d5ae914d	hoch	1.16	30	weiblich
0ebe68cd-b93c-4009-b88a-61f48269d12f	hoch	1.17	31	weiblich
75a95427-c716-4367-9ad5-d514384889f4	hoch	1.18	32	weiblich
c8906783-16cb-40b3-82df-cb670afbedb7	hoch	1.19	33	weiblich
2cad0ca1-101b-4847-9992-b8227e8f32c7	hoch	1.19	34	weiblich
a23c1dc5-c1f5-4148-9425-86f5364d932f	hoch	1.2	35	weiblich
0da6ec72-f39d-48ee-b7bc-da857370a5b3	hoch	1.21	36	weiblich
68259fb9-f3c8-43b3-8542-58c0366b0847	hoch	1.22	37	weiblich
9f60e5f9-691a-4244-b6b3-b01f779bc62b	hoch	1.23	38	weiblich
35e84711-0c4c-4269-926d-59b9d2e3bb5a	hoch	1.23	39	weiblich
f4bf1597-6d87-44b9-9b78-e2501632c40d	hoch	1.24	40	weiblich
dabfc038-68f9-496a-a132-db4313ce731b	hoch	1.25	41	weiblich
914b2ccf-0351-4514-8787-f10fdb0ac2bd	hoch	1.26	42	weiblich
dc09c009-857a-46b0-9f19-765e4b02bc42	hoch	1.27	43	weiblich
fa918806-f7ab-4405-86bc-91b6f4586df9	hoch	1.27	44	weiblich
f4114057-fc38-427d-bf66-067ec9ede74b	hoch	1.28	45	weiblich
da20ac93-d0d5-46c2-baef-343488713ef6	hoch	1.29	46	weiblich
190ac176-034d-4181-80c6-556ad0d4efea	hoch	1.3	47	weiblich
168f24b0-872f-4365-9f6b-6d1b41488c02	hoch	1.31	48	weiblich
b232e01f-4c6d-4c74-9b88-b4e33e7c9535	hoch	1.31	49	weiblich
292d4732-d133-45ba-9258-77b822e9bd4c	hoch	1.32	50	weiblich
ca307def-8b0a-43c2-b1ef-5f6ecf806c22	hoch	1.33	51	weiblich
2c4486d2-79fb-4fdc-bc55-167f90a0e829	hoch	1.34	52	weiblich
55bb9467-4d4d-4d28-94f4-3d5a40adf271	hoch	1.35	53	weiblich
84845d37-e1b8-4ff4-93d6-a002569540af	hoch	1.36	54	weiblich
9bbc68cf-6713-4b19-897e-1f59509b7e4b	hoch	1.37	55	weiblich
6d0628ce-7781-4196-a878-8cdfbcfa6ce6	hoch	1.37	56	weiblich
88c63177-ec0f-43df-8441-4423b8242949	hoch	1.38	57	weiblich
1298c5be-c979-49ad-be82-644844868426	hoch	1.39	58	weiblich
3c4ff8f2-eb7f-4bd3-9eb4-ef3f1b772637	hoch	1.4	59	weiblich
1bcc581f-2534-4581-aa8c-67960b48e19f	hoch	1.41	60	weiblich
33911e9e-9215-4bf9-b66d-9d03e5bba373	hoch	1.42	61	weiblich
e993c686-051a-4add-a5ac-2d2d482465bd	hoch	1.42	62	weiblich
965e45d0-2e10-4109-9bfd-386b73ae8181	hoch	1.43	63	weiblich
9fdbc99d-152e-4a1f-843e-7ee255eccc1b	hoch	1.44	64	weiblich
deba2458-2c61-4487-9fd9-184a61394ec9	hoch	1.45	65	weiblich
97cb6e40-503b-455c-8f3a-9723f091d527	hoch	1.46	66	weiblich
796c48f6-7078-40b3-bd1c-1a47c9de9179	hoch	1.47	67	weiblich
8770f09f-7572-45a8-99c0-0659d29e33ad	hoch	1.48	68	weiblich
8cbae383-8dff-40fd-a6ce-34df6c49d114	hoch	1.49	69	weiblich
4db9d2ab-923b-41a0-bd0f-6c28390d8823	hoch	1.49	70	weiblich
81ae16ef-a54f-4485-adfc-12636288999c	hoch	1.5	71	weiblich
931f778e-1060-4669-9b12-9939d6abfb72	hoch	1.51	72	weiblich
b225f1f1-c01e-4693-b6eb-3fb3886271dd	hoch	1.52	73	weiblich
0831a5e8-5f79-4ad7-8b22-7d1713458977	hoch	1.53	74	weiblich
2b194381-2a45-428a-928a-dfb8cf3f6f4c	hoch	1.54	75	weiblich
04ca1fc3-a537-452f-922f-474314962ebc	hoch	1.55	76	weiblich
dd1e5dbc-9b52-41ef-a8b6-e58113790536	hoch	1.56	77	weiblich
b2b53980-acb2-42f9-97b8-830811301463	hoch	1.57	78	weiblich
cc759080-5972-475d-9ce9-030618df8128	hoch	1.57	79	weiblich
70efb2f1-9b7f-4565-8cf7-df29042c6ec1	hoch	1.58	80	weiblich
2dfb0610-d0e0-4112-aa8a-5b92f88aae4b	hoch	1.59	81	weiblich
08da1a92-a55d-4f3c-9dbb-eb44b46625b7	hoch	1.6	82	weiblich
4c54e89b-cd4d-4277-988c-d8bf445e3929	hoch	1.61	83	weiblich
ee478fb4-6c81-48ef-8d1e-72a375380854	hoch	1.62	84	weiblich
bdf2efe8-c709-482f-b802-a4bfc02b78ca	hoch	1.63	85	weiblich
ad0c0a24-a6b2-4a18-9b36-6c7d6640d882	hoch	1.64	86	weiblich
e07928ab-11c7-47f4-a2ba-3179b31f32e6	hoch	1.65	87	weiblich
f18dd560-584b-4680-9607-e45949da176f	hoch	1.66	88	weiblich
6cb3f2bc-d194-4550-a05a-501a07db4b2b	hoch	1.67	89	weiblich
3f1110b9-6cc1-4e94-a20a-84f96f0f94eb	hoch	1.68	90	weiblich
de74d3ed-b5d6-4176-bb2b-1d6344ca580b	hoch	1.69	91	weiblich
0f6a000c-e78e-4d4a-bb1b-f266629ddd6d	hoch	1.69	92	weiblich
a51a3bc4-7ebf-4c21-9a55-d2f62f1ef7be	hoch	1.7	93	weiblich
5afc4ec1-c297-49c8-83da-31fc520dace6	hoch	1.71	94	weiblich
5c15b008-6cbf-47af-b107-ee340bf6d3b1	hoch	1.72	95	weiblich
3321e366-783b-429c-955d-789bc9ed528b	hoch	1.73	96	weiblich
c9a7b4a3-940d-42dd-9ed3-959261617990	hoch	1.74	97	weiblich
6771f774-2c60-40e0-9055-4e9d10de42ca	hoch	1.75	98	weiblich
0cb6af6e-82d5-4982-8571-cc54f50b5f77	hoch	1.76	99	weiblich
8578eda7-3b3d-4e93-85b3-491ef13cbdf7	hoch	1.77	100	weiblich
6df3f0a1-aa9a-4ca8-834c-a876129a7e4d	speer	12.64	19	maennlich
970e9ca6-691f-467d-918d-1455b7ea5ae3	speer	13.03	20	maennlich
60d26608-dab8-4195-9dbc-8e90802ba808	speer	13.45	21	maennlich
0d6ad43e-9d7a-4846-a07b-b6f139eabf65	speer	13.87	22	maennlich
b8796744-ccd1-478b-93d0-be2bfff0db68	speer	14.29	23	maennlich
7e815b7c-fa4e-44ed-8443-7ad463893422	speer	14.72	24	maennlich
3116145b-0e69-430b-9186-014b16f2d28b	speer	15.16	25	maennlich
08e41a11-edf5-4181-9578-3449b1ddca25	speer	15.6	26	maennlich
86da0800-3fea-462a-9196-1ea7d8806abc	speer	15.99	27	maennlich
198e74d3-5089-41dd-818c-73ba28329769	speer	16.49	28	maennlich
a8041de2-090b-4fc1-ac3c-0bce6f11bb95	speer	16.95	29	maennlich
4ce756e8-2262-4d87-a2d3-83be6c710161	speer	17.41	30	maennlich
c3ec9117-7ea7-40d2-ab9b-f3e96755318e	speer	17.87	31	maennlich
465dffb2-531c-4d8a-bc08-697855501037	speer	18.34	32	maennlich
54df93af-5517-4fa8-8ed7-61928465244a	speer	18.81	33	maennlich
50dae015-2944-4e0e-bab7-47ed8f10c2ba	speer	19.29	34	maennlich
6e3477d8-ccb8-4b73-b8f6-0a20d250f751	speer	19.77	35	maennlich
4d2183d6-06d7-40bc-9856-f7ce9990c6af	speer	20.26	36	maennlich
0f57cb37-60f7-47fa-9dff-9e3f8f73fe69	speer	20.75	37	maennlich
3431bd23-0a4a-405a-a38b-2678162e719d	speer	21.25	38	maennlich
05e232e3-99af-43fc-aed4-e24781c84de4	speer	21.75	39	maennlich
5df59595-7b11-41c4-99dc-6b5c23179ae4	speer	22.25	40	maennlich
ed5601ac-3185-4df2-8cef-042e7cd9bbbe	speer	22.76	41	maennlich
3680d36c-623d-4378-8c93-947b08d4c93f	speer	23.28	42	maennlich
c27dcb18-1ebe-4cd6-892e-19c7c215ce1c	speer	23.8	43	maennlich
d465d816-28d7-4e1a-8385-0370134c4a72	speer	24.32	44	maennlich
588a436e-7365-4b25-93fa-83de702974c7	speer	24.85	45	maennlich
bd893bfb-28e0-4c8a-b065-084d4e468cc0	speer	25.39	46	maennlich
0803d88c-1723-48f2-845e-24d6ed5b77b0	speer	25.93	47	maennlich
9af4cddb-4a54-4f94-ad8b-b70021f7f9f6	speer	26.47	48	maennlich
f5a96438-4725-46b0-afe0-9f21002cf0cf	speer	26.99	49	maennlich
18ea1992-4943-405a-99e9-2f6117b185cf	speer	27.57	50	maennlich
8ab3765c-cd26-4b1e-a2f8-088c3b17dcd9	speer	28.13	51	maennlich
7ad1828b-8d24-4e00-9da3-78bcd7270fb8	speer	28.69	52	maennlich
305f77c2-4fd2-48ce-99ba-833512b5e617	speer	29.26	53	maennlich
cccdef3c-2437-49d0-940a-c032c787311c	speer	29.84	54	maennlich
d1ac754f-2198-4a4f-b6d0-7f97206360f1	speer	30.41	55	maennlich
09c853a7-81f7-4e3b-97d3-155433a3edc6	speer	30.99	56	maennlich
00830268-1fc7-4b7e-95a4-d6441877ef57	speer	31.58	57	maennlich
44fd6ed9-ccf5-4e80-9ec4-bea229c37d57	speer	32.17	58	maennlich
c5dc5e3d-a67c-43e4-a9c8-e340af8341ad	speer	32.77	59	maennlich
79004828-69b3-4621-a470-0a37e894ad2e	speer	33.37	60	maennlich
f5546935-80fa-4108-a85d-6dce29b3eed9	speer	33.98	61	maennlich
975ffce5-40da-4735-a9c1-7ec9ccb1348c	speer	34.59	62	maennlich
f8d5963f-88bf-445e-8c06-e31e7aa50c3a	speer	35.2	63	maennlich
f52a98ea-c42c-4bff-99ef-801a220c7bea	speer	35.82	64	maennlich
10aebb74-8f6e-4aa4-8a7c-24297dc725c1	speer	36.45	65	maennlich
a61e8739-b730-4aee-84a8-ab9ec8047792	speer	37.07	66	maennlich
39018088-044a-496c-8621-987be4be8a1e	speer	37.71	67	maennlich
08a0b347-2f1e-45d1-ac76-bc306b3ccedc	speer	38.35	68	maennlich
cc9fe1e4-0261-4cae-b115-ad50d60825d7	speer	38.99	69	maennlich
f03bdab9-5681-4073-aa1f-8f041998f806	speer	39.64	70	maennlich
b8c9582a-fff2-4130-846a-630f2e2b36a9	speer	40.29	71	maennlich
7a443845-c528-4992-9424-4db989587292	speer	40.95	72	maennlich
15b207d9-2f72-44b9-87eb-177dced2431b	speer	41.61	73	maennlich
9af35eba-a6f2-4255-a40f-0821b0caa372	speer	42.3	74	maennlich
3a12c2ea-c230-448f-bf39-edac2dfbcc0b	speer	42.95	75	maennlich
4522c199-8754-4389-b6c1-7a325708c332	speer	43.63	76	maennlich
3c11052b-8ead-4bd7-ab2b-cbcc906e0382	speer	44.31	77	maennlich
00631cf0-96ca-4e82-a6a9-9c9b2a0fca94	speer	45	78	maennlich
7b4f3023-bdb4-40e8-bf7b-0f67a7ab0340	speer	45.69	79	maennlich
a1488470-85dd-4d76-ae1b-533a05fad619	speer	46.38	80	maennlich
632de6f1-dbb1-43f4-ae81-957f7da2da89	speer	47.08	81	maennlich
ec4a8051-ab19-4463-9a03-e809269f70d6	speer	47.79	82	maennlich
d67c2edc-a1ce-4f27-8b09-e8ffebb8b7f9	speer	48.5	83	maennlich
df30de80-a029-42bd-81cf-abe15b895722	speer	49.21	84	maennlich
3fe729fd-e30e-4012-a33e-84e6fc66a390	speer	49.93	85	maennlich
f9c0b91a-89d8-4cc9-adb5-cccbd55dda20	speer	50.66	86	maennlich
008bd31d-719a-4b8e-a240-0a772280af3e	speer	51.39	87	maennlich
304333da-2c41-4c07-9af2-d28b2dc564e2	speer	52.12	88	maennlich
2ac9d3be-d6e2-4032-9494-ecaf37c96741	speer	52.86	89	maennlich
d7be12e1-c835-43ea-b1ec-ba2583ad5983	speer	53.6	90	maennlich
96fa34c7-6e51-49a5-8a6c-d2c8d2ad630b	speer	54.35	91	maennlich
a78d971c-9edc-4bb5-91e3-61b3ed630633	speer	55.1	92	maennlich
63a048dd-8964-4fd9-b44d-52418d406527	speer	55.86	93	maennlich
aa70caa2-a171-4307-9739-709c4cc9d3c6	speer	56.62	94	maennlich
df5e75b6-0727-41af-acbb-ba215146fde5	speer	57.39	95	maennlich
5610b8c5-97cf-4c42-876e-05a2e70e2c9d	speer	58.16	96	maennlich
6e26ff9b-3b2f-4d11-a78d-824e92ce6353	speer	58.94	97	maennlich
3a49a30b-0570-44c2-bbea-ccaf6444ebd3	speer	59.72	98	maennlich
af06cdf1-2143-4525-bbba-8f56c2d31a67	speer	60.5	99	maennlich
0a083350-11d0-416a-9719-cf8177b48f84	speer	61.3	100	maennlich
a73bc417-6552-4766-935e-4bf970ca6dbd	speer	12.45	33	weiblich
c88c849b-33ce-4289-b63d-41266e18834e	speer	12.78	34	weiblich
d7a6020c-5705-408c-8b6a-98d5adf0299c	speer	13.13	35	weiblich
91cd05b8-e910-4cfe-a2a6-51fa154b7a55	speer	13.44	36	weiblich
d4fd9d62-d996-4683-84db-aaee915fab25	speer	13.78	37	weiblich
dc937ea7-eef7-4503-ab4a-f3ef7c37d588	speer	14.12	38	weiblich
54867618-72a5-40c7-a139-c6e929b46e59	speer	14.46	39	weiblich
bab168d3-7ae8-4455-8b46-4af712a12817	speer	14.81	40	weiblich
a3ac3787-5686-489a-9748-ee97dbe858c4	speer	15.16	41	weiblich
0f547507-c876-450b-9d06-9aedf180675f	speer	15.56	42	weiblich
852974eb-3937-442a-a3f3-e09b390c08f8	speer	15.87	43	weiblich
f34c013c-e23c-476d-bccb-57e687e43476	speer	16.23	44	weiblich
dd9c1ed7-c029-46c0-9888-e0df022b8245	speer	16.59	45	weiblich
3427bba1-7804-4fd0-b267-9e2da8b93c61	speer	16.96	46	weiblich
14f7eb1b-0635-4de2-bdf6-1a0ca95dcd00	speer	17.33	47	weiblich
e05d0b7d-1862-43a9-b46c-399d3609bd58	speer	17.76	48	weiblich
6ba552c0-e40b-47cf-a3a7-866cf45658be	speer	18.02	49	weiblich
e06af947-6cfa-48ed-bee8-5ca5e5d2df93	speer	18.46	50	weiblich
dcd69ffa-19b0-40a8-977d-ad32d78918b7	speer	18.84	51	weiblich
2df2f48e-5d59-485b-a490-3cec96c8aac3	speer	19.23	52	weiblich
8994694f-e3e7-492a-9e9e-fcf5d61e72d6	speer	19.61	53	weiblich
fc236548-97cf-4ef2-82e8-9a94411338c2	speer	20.01	54	weiblich
32ab0ad6-6d3d-47cc-a727-cc684c8e2d79	speer	20.4	55	weiblich
c920d2cf-97d7-413a-b998-7b1e5f202368	speer	20.8	56	weiblich
3c723680-b7f0-435d-bdc3-790b2680c00c	speer	21.2	57	weiblich
5256886c-ed00-445b-87b3-4b521ec7eab2	speer	21.61	58	weiblich
560dc2e6-ebf2-4042-8e8a-8970e6956a28	speer	22	59	weiblich
bd306c7b-248b-4879-a0b4-545f5d5e24ca	speer	22.43	60	weiblich
afcc1432-fc4e-4c2d-99f8-c215484f52cc	speer	22.84	61	weiblich
e3b1b12f-70ae-417d-98d9-7ca40481ff9d	speer	23.26	62	weiblich
108e499a-3227-4662-83e5-4b92692cc262	speer	23.68	63	weiblich
51831f22-7018-47d1-ad5f-ff49726e6e2b	speer	24.13	64	weiblich
5beed2eb-d9b5-4d63-b159-fb9129db81dc	speer	24.34	65	weiblich
c6cecd37-8f49-4402-ad98-b06f4cfed249	speer	24.97	66	weiblich
766e48e3-8deb-477f-a823-5dc606867cf3	speer	25.4	67	weiblich
8c93cbca-0a01-4236-87a4-40d5f3593d70	speer	25.84	68	weiblich
b8ebf4d9-4c2d-4074-afeb-481b745c0f23	speer	26.28	69	weiblich
50483ddf-532c-4aab-ab41-43c7adcce607	speer	26.72	70	weiblich
3206563e-1d47-4fee-b1c1-c0c0230979c2	speer	27.17	71	weiblich
2dfcd022-1fcb-43c4-8507-e5ec7dca7b63	speer	27.62	72	weiblich
083c3570-172a-436d-bf6a-fb71ec9e089c	speer	28.13	73	weiblich
c729398f-cb2c-44e9-b3a8-17e50d7d861c	speer	28.53	74	weiblich
dcc13784-7078-44b2-b001-8e04fc4e9281	speer	28.99	75	weiblich
4a1c379b-8f9a-4d41-9c05-4cdfc60eccf9	speer	29.46	76	weiblich
ec7332ea-6cb7-4593-9d4f-7a112276321c	speer	29.29	77	weiblich
4eaf4051-e3a8-427f-b998-a32e183ea3b2	speer	30.39	78	weiblich
5d7f94af-62ff-431f-9acf-e65d7f144707	speer	30.86	79	weiblich
fd7f26b9-1f49-4711-b1c3-aa90549b3390	speer	31.34	80	weiblich
6d891a3c-a484-41be-b0be-bc36b50766ff	speer	31.82	81	weiblich
f78163d6-12e5-4594-af89-89f8224bcf76	speer	32.3	82	weiblich
08572550-622e-4b85-82e0-1dc3a475d6bc	speer	32.79	83	weiblich
5c4818e1-09f9-4236-9ae8-d3fabba152e1	speer	33.28	84	weiblich
fa23340b-f1d6-4d7d-bc42-a84fbf66e7d2	speer	33.77	85	weiblich
ca2e1822-de5d-4041-b356-c02935204995	speer	34.27	86	weiblich
0e702885-163d-4883-8f31-1919326ca95a	speer	34.77	87	weiblich
0f5f73e0-5dce-4740-8f1f-52edf9a51b90	speer	35.27	88	weiblich
00a1dd2f-39be-4f98-9abc-3dcaa250121b	speer	35.77	89	weiblich
8b3077ff-48dc-40eb-b160-b3da9faac86b	speer	36.28	90	weiblich
e3860b71-4ba7-436d-87c4-51b52e549f2e	speer	36.79	91	weiblich
cce4c927-c3d5-4371-a72c-0015434d6af4	speer	37.31	92	weiblich
4cc8b57e-ee7d-40f9-aaf9-f03686d3387d	speer	37.83	93	weiblich
e0f44a24-5aa5-4b41-854c-a20b54bda4b3	speer	38.35	94	weiblich
424b93f1-2c4b-44b9-9346-c6efc05a3128	speer	38.87	95	weiblich
f64f1610-e00c-4c60-a8a3-c123970c7e24	speer	39.4	96	weiblich
545c1adb-2e65-41c9-bbea-84d8dd8bee71	speer	39.93	97	weiblich
1f71bb13-5b0f-4816-b92c-3c8396376b24	speer	40.47	98	weiblich
2b8b501b-5de6-46d3-8729-358d382b067d	speer	41	99	weiblich
fe821420-bf19-4b60-9168-95d87baf5662	speer	41.55	100	weiblich
659bcc42-c156-4b96-910d-cf7375b16c35	speer	3.67	1	weiblich
ecf2ab05-4cfc-45dd-a0a7-231b6f0b0402	speer	3.89	2	weiblich
b66aad7b-9489-4ec2-ab4e-5e82a1a143d2	speer	4.12	3	weiblich
a3a88159-a3d6-4b7e-8fbf-6ce415fb19e1	speer	4.35	4	weiblich
ba397c06-4c99-4d4c-b79f-f1333ad416a0	speer	4.53	5	weiblich
65814f73-f649-4ad2-9fab-23421568a4d4	speer	4.82	6	weiblich
1c6a3cf5-c7fc-4a27-a33d-4e058365d86b	speer	5.06	7	weiblich
59be0c3e-5f0d-4f7f-be5b-f9f94e65be06	speer	5.31	8	weiblich
78d24900-425c-407b-af34-415d920d2657	speer	5.55	9	weiblich
6ca955b7-4f87-4f24-b2b7-4d79cd70bd17	speer	5.86	10	weiblich
125759c3-f560-4cfb-9131-d92bfba5af13	speer	6.06	11	weiblich
bafe1d76-8f07-49ac-9202-7dead6a427cd	speer	6.31	12	weiblich
4aba74a8-49e6-4e37-ba69-b526e3160de8	speer	6.57	13	weiblich
88d84e53-54ef-4b66-bdc5-78e84ef50cde	speer	6.84	14	weiblich
fb8544e9-b81f-4537-8d8f-b412c741bd40	speer	7.1	15	weiblich
ff85fbc7-ddd0-4083-a67c-378d5e8916d0	speer	7.37	16	weiblich
026ec4e3-806c-42e5-a0eb-6084fe46438b	speer	7.65	17	weiblich
23a53b93-5db1-49c3-a613-c7a11444fb56	speer	7.92	18	weiblich
fd93ea1a-db6e-4523-a5c9-68c3af58f805	speer	8.2	19	weiblich
dd1ce851-a652-47b5-a14d-c1ffa1cd7d0b	speer	8.48	20	weiblich
110e47bc-47c1-45e9-92ce-2ed4838ff079	speer	8.77	21	weiblich
37a31638-b1b3-4986-8f0c-a16fbf9ee0d0	speer	9.06	22	weiblich
2b06ae69-5bb4-4e4f-bf25-4c04f63497f7	speer	9.35	23	weiblich
d7293e06-f384-465d-a7d4-d38f8784a8df	speer	9.64	24	weiblich
20adb16a-8070-4195-82c7-caef603a6e69	speer	9.94	25	weiblich
84cf505a-84ea-4077-bd31-f730213e526a	speer	10.25	26	weiblich
34c8a67b-5830-4b24-9e26-04fd18fdafd0	speer	10.55	27	weiblich
8b3897d3-eb81-4109-bada-a2ebdbab720f	speer	10.88	28	weiblich
6aaa7890-0f94-4c50-8d74-7a68779c43aa	speer	11.17	29	weiblich
dca8139b-4712-445b-ad1e-6bd1f1985a60	speer	11.48	30	weiblich
fc12781c-2963-4d58-829b-f2e0377652d3	speer	11.86	31	weiblich
fa849dcc-17ac-45a8-935f-20002ea41e48	speer	12.12	32	weiblich
b960f034-2e79-47c9-905f-ee632e28c6dd	kugel	4.68	1	weiblich
4255b9fd-dbc6-4d9d-87b9-585070a5b969	kugel	4.74	2	weiblich
aa7fed56-6d5e-430c-a8ae-1a717972b6bd	kugel	4.79	3	weiblich
7bb2e6e7-6e9e-4e22-bc99-b43bc48118f1	kugel	4.85	4	weiblich
9b740bce-5b00-41fb-9995-9ef0a8005366	kugel	4.91	5	weiblich
9485cab6-760d-4e23-88c4-cc98fee7c475	kugel	4.96	6	weiblich
ba785810-2c52-4088-89a0-743823b71b81	kugel	5.02	7	weiblich
8307fa08-34ff-47fc-9872-256da14403b3	kugel	5.08	8	weiblich
7e75e4a3-bd33-40be-8316-0fd51142b3c1	kugel	5.14	9	weiblich
d467a8a9-4780-433c-999c-95be192a16a5	kugel	5.19	10	weiblich
b429b9cc-db7d-40df-882e-4b99472b0d5e	kugel	5.25	11	weiblich
bef424ff-4930-43f9-96ba-b3862735a772	kugel	5.31	12	weiblich
560946b6-24d5-4475-bdd5-cf25ad747727	kugel	5.37	13	weiblich
e2af2b46-7128-42bf-9e28-4721d7d84749	kugel	5.43	14	weiblich
7d0da065-071c-4643-aa6e-3a84e3892a9d	kugel	5.49	15	weiblich
bafbc0f4-4a51-4c11-bbde-9ac77f790f35	kugel	5.55	16	weiblich
406dc906-afe7-4aec-b48b-0a6107868d55	kugel	5.61	17	weiblich
159a1448-3d74-4406-896f-54769bd1e193	kugel	5.67	18	weiblich
be4ab785-5553-40e5-9993-03e921d5b710	kugel	5.73	19	weiblich
1d774c97-5b52-4ac4-8a81-bf7b2e9aa78f	kugel	5.79	20	weiblich
\.


--
-- Data for Name: profiles; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.profiles (id, role, username, password) FROM stdin;
254611ba-b706-44bb-9107-592ce58280ae	teacher	lehrerpass	$2b$10$043PSaolxboRHZEK8CWuCuVHI0reCIZkLDw.C0tDNMOIFm0rmfVlK
78404f03-c2ac-4653-8e72-2d5383635a9f	assistant	helferpass	$2b$10$aVhXNVODz2YjnJ31QdN3FuwLazWb9hT2SZPBFmnJYay7RdPD3y0aW
\.

--
-- Data for Name: sportdays; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.sportdays (id, created_at, date) FROM stdin;
1	2025-04-07 13:43:16.907411+00	2025-06-24
\.


--
-- Data for Name: sports; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.sports (id, name, code, measure, mesure_unit_short, attempts, check_fail, time_measure, svg_url) FROM stdin;
fbf1f2fa-3c4f-480d-b67d-e98a015c8543	80m	80m	sekunden	sek	1	f	t	/icons/80m.svg
eded7669-870b-4a5b-86a8-5172d4471f7d	Hochsprung	hoch	meter	m	6	t	f	/icons/hoch.svg
36eb0b0d-f7e9-409a-a0d9-1626b77cbf94	Hürdenlauf	huerdenlauf	sekunden	sek	1	f	t	/icons/huerdenlauf.svg
6cf2807c-c25a-4901-abb6-8ce2f2f01425	Speerwurf	speer	meter	m	1	f	f	/icons/speer.svg
112fcd9d-e1f2-4222-8124-fe81ea6b8f4f	Kugelstossen	kugel	meter	m	1	f	f	/icons/kugel.svg
\.

--
-- Name: results_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.results_id_seq', 1428, true);


--
-- Name: sportdays_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.sportdays_id_seq', 1, false);


--
-- Name: grades_table grades_table_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.grades_table
    ADD CONSTRAINT grades_table_pkey PRIMARY KEY (id);


--
-- Name: points_table points_table_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.points_table
    ADD CONSTRAINT points_table_pkey PRIMARY KEY (id);


--
-- Name: profiles profiles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.profiles
    ADD CONSTRAINT profiles_pkey PRIMARY KEY (id);


--
-- Name: profiles profiles_username_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.profiles
    ADD CONSTRAINT profiles_username_key UNIQUE (username);


--
-- Name: results results_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.results
    ADD CONSTRAINT results_pkey PRIMARY KEY (id);


--
-- Name: sportdays sportdays_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sportdays
    ADD CONSTRAINT sportdays_pkey PRIMARY KEY (id);


--
-- Name: sports sports_code_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sports
    ADD CONSTRAINT sports_code_key UNIQUE (code);


--
-- Name: sports sports_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sports
    ADD CONSTRAINT sports_name_key UNIQUE (name);


--
-- Name: sports sports_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sports
    ADD CONSTRAINT sports_pkey PRIMARY KEY (id);


--
-- Name: students students_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.students
    ADD CONSTRAINT students_pkey PRIMARY KEY (id);


--
-- Name: results results_student_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.results
    ADD CONSTRAINT results_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.students(id) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

\unrestrict AQ0bZAZyviCpome1xLcGiXdb2D8HXXeOUVNpwO8NFzIN5Lx2PyAIBqlfIMscbqe

